### ISSUE TITLE
External Git changes cause tracebacks

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#1007]
External changes to the Git repository can cause tracebacks within the Git code, errors pointing to problems with connecting/disconnecting signals.

This is just a preliminary issue to create a place to collect examples to reproduce the issue. I'll have to do more research on it.

**Comment by uliska** [comment]
Thanks for the concrete report. I could fix this quite easily (although I'm not 100% sure I really did "the right thing"). It will not fix the other problems mentioned on the Frescobaldi list, though.

**Comment by uliska** [comment]
Also reported by Federico:

> Another minor problem:

> - launch Frescobaldi and open the file you want to edit
> - create a new branch on the terminal
> - edit the document and save it

> I could not see the colors in the gutter.
> The document was not saved.

> Don't know if it's because it doesn't like my branch name:

```
Traceback (most recent call last):
 File "/home/fede/src/frescobaldi/frescobaldi_app/tabbar.py", line 125, in slotTabCloseRequested
   self.window().closeDocument(self.docs[index])
 File "/home/fede/src/frescobaldi/frescobaldi_app/mainwindow.py", line 589, in closeDocument
   doc.close()
 File "/home/fede/src/frescobaldi/frescobaldi_app/document.py", line 114, in close
   app.documentClosed(self)
 File "/home/fede/src/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
   l.call(args, kwargs)
 File "/home/fede/src/frescobaldi/frescobaldi_app/signals.py", line 308, in call
   return self.func(obj, *args[self.argslice], **kwargs)
 File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 334, in slotDocumentClosed
   space.removeDocument(doc)
 File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 169, in removeDocument
   self.disconnectView(self.activeView())
 File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 195, in disconnectView
   view.cursorPositionChanged.disconnect(self.updateCursorPosition)
TypeError: 'method' object is not connected
Traceback (most recent call last):
 File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/gitrepo.py", line 179, in get_remote_branches
   self._tracked_remotes[local_branch]['remote_branch'] = 'local'
KeyError: 'upgrade-1.9'
```

> When I restart Frescobaldi with upgrade-1.9 already checked out, everything works correctly.
>
> Sorry for the quick and dirty report, but I'm about to going to the beach 

I'm not fully clear what you mean here. Do you create a branch and check it out? or only create it? Either way, I can't reproduce the problem. Maybe it has been fixed together with the previous problem?

**Comment by uliska** [comment]
Also reported by Federico:

> Now after adding some files (git add ...) in a terminal, I get this internal error message window in Frescobaldi:

```
Traceback (most recent call last):
 File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/gitrepo.py", line 249, in <lambda>
   self._documents[relative_path].update(repoChanged = True)
KeyError: 'collections/kv487/kv487-lys/no1.ly'
```

> (several times for several files)
>
> I'm not sure if it can be reproduced 100% of times.

I'm sorry but I can't reproduce it, neither with the newest commit nor with the previous state. @fedelibre Could you investigate more and produce a concrete example (ideally from a publicly available repository)?

**Comment by fedelibre** [comment]
Let's forget what I reported on the list. Probably other errors were caused by the main problem, that you should have fixed. I'll confirm later.

Let me report what's happening now. I think I found another problem.
It might be worth adding that I'm using Frescobaldi sessions. In my current session (called mutopia) I had two files of Bach open and saved to the session. Today I closed them and opened another file.
Then I changed from master branch to the previously created update-2.x-guitar branch and I got this error:

```
Traceback (most recent call last):
  File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/gitrepo.py", line 251, in <lambda>
    self._documents[relative_path].update(repoChanged = True)
KeyError: 'ftp/BachJS/BWV817/french-suite-6/french-suite-6-lys/bach-french-suite-6-sarabande.ly'

Traceback (most recent call last):
  File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/gitrepo.py", line 251, in <lambda>
    self._documents[relative_path].update(repoChanged = True)
KeyError: 'ftp/BachJS/BWV817/french-suite-6/french-suite-6-lys/bach-french-suite-6-polonaise.ly'
```

these are the two files previously open and saved to the mutopia session.

**Comment by fedelibre** [comment]
I've now tried to create and checkout a new branch. I get the same errors as above.

When I close Frescobaldi I get also this error:

```
Traceback (most recent call last):
  File "/home/fede/src/frescobaldi/frescobaldi_app/mainwindow.py", line 307, in closeEvent
    if not lastWindow or self.queryClose():
  File "/home/fede/src/frescobaldi/frescobaldi_app/mainwindow.py", line 325, in queryClose
    doc.close()
  File "/home/fede/src/frescobaldi/frescobaldi_app/document.py", line 114, in close
    app.documentClosed(self)
  File "/home/fede/src/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/home/fede/src/frescobaldi/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 334, in slotDocumentClosed
    space.removeDocument(doc)
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 169, in removeDocument
    self.disconnectView(self.activeView())
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 199, in disconnectView
    view.vcsRepoTracker.repoChanged.disconnect(self.updateVcsRepoStatus)
TypeError: 'method' object is not connected
```

**Comment by fedelibre** [comment]
Now after restarting I can safely create and change branches without any error.
The problem is definitely related to sessions saving.

I forgot to say that my tests in my last three comments were made after pulling your latest commit.

**Comment by uliska** [comment]
The last one looks like #1009 which I've just discovered. Looks like this one isn't related to branches but to opening files.

**Comment by uliska** [comment]
@fedelibre I just tried to review this issue but found it complicated to reconstruct all the issues you reported, as they maybe are specific to your set-up and file context.

My impression that this problem has disappeared through the recent commits, and I would be glad if you could try to reproduce the steps that led to the errors you reported.

**Comment by fedelibre** [comment]
I cannot reproduce the issues anymore.
However, it seems that VCS features are disabled, as I cannot see anything in the gutter while modifying a document.

**Comment by uliska** [comment]
See my comment to your new issue

Am 25. Oktober 2017 06:43:32 MESZ schrieb Federico Bruni <notifications@github.com>:
>I cannot reproduce the issues anymore.
>However, it seems that VCS features are disabled, as I cannot see
>anything in the gutter while modifying a document.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/wbsoft/frescobaldi/issues/1007#issuecomment-339212830

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fedelibre** [comment]
#1021 explains why VCS features are not working. I'll check this issue again once that is fixed.

**Comment by fedelibre** [comment]
Now I can test it and I can say that I cannot reproduce the issues.

**Comment by uliska** [comment]
Great!
Then I can close the issue (we can always reopen it or create new issues)
