### ISSUE TITLE
'import os' forgotten in vcs/abstractrepo.py?

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#1021]
Today I've pulled the changes made in the last month in the rewrite-vcs branch and I get this error:

```
[frescobaldi (rewrite-vcs=)]$ python3 frescobaldi
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "frescobaldi", line 11, in <module>
    main.main()                     # Parse command line, create windows etc
  File "/home/fede/src/frescobaldi/frescobaldi_app/main.py", line 267, in main
    win.setCurrentDocument(doc)
  File "/home/fede/src/frescobaldi/frescobaldi_app/mainwindow.py", line 181, in setCurrentDocument
    self.viewManager.setCurrentDocument(doc, findOpenView)
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 318, in setCurrentDocument
    self.activeViewSpace().showDocument(doc)
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 164, in showDocument
    self.connectView(view)
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 190, in connectView
    self.connectVcsLabels(view)
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 205, in connectVcsLabels
    self.updateStatusBar()
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 227, in updateStatusBar
    self.updateVcsRepoStatus()
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 235, in updateVcsRepoStatus
    name = self.activeView().vcsRepoTracker.name()
  File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/abstractrepo.py", line 144, in name
    _, name = os.path.split(self.root_path)
NameError: name 'os' is not defined
```

It seems that os is not imported...  This change fixed it:

```
[frescobaldi (rewrite-vcs *=)]$ git diff
diff --git a/frescobaldi_app/vcs/abstractrepo.py b/frescobaldi_app/vcs/abstractrepo.py
index 6b60cf92..d79fc44a 100644
--- a/frescobaldi_app/vcs/abstractrepo.py
+++ b/frescobaldi_app/vcs/abstractrepo.py
@@ -24,7 +24,7 @@ VCS interface (application and documents)
 from abc import ABCMeta, abstractmethod
 
 from PyQt5.QtCore import QObject
-
+import os
 
 class Repo(QObject):
     """
```

**Comment by uliska** [comment]
Oh sorry, it seems I have forgotten to push the corresponding fix yesterday.
But you should check out https://github.com/wbsoft/frescobaldi/commit/c51175d45c82a956cb5d1432efa4b7a4c97a8fb9 anyway - I noticed some fundamentall issues with the refactoring. I'll work on it today but my computer is offline.

**Comment by fedelibre** [comment]
Ok, now I see why VCS features did not work.
I've checked out that commit and now I get another error:

```
[frescobaldi ((c51175d4...))]$ python3 frescobaldi
Traceback (most recent call last):
  File "frescobaldi", line 11, in <module>
    main.main()                     # Parse command line, create windows etc
  File "/home/fede/src/frescobaldi/frescobaldi_app/main.py", line 247, in main
    win = mainwindow.MainWindow()
  File "/home/fede/src/frescobaldi/frescobaldi_app/mainwindow.py", line 154, in __init__
    self.updateWindowTitle()
  File "/home/fede/src/frescobaldi/frescobaldi_app/mainwindow.py", line 282, in updateWindowTitle
    window_title += " " + vcs.app_active_branch_window_title()
  File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/__init__.py", line 94, in app_active_branch_window_title
    remote=app_repo.tracked_remote_label(git_branch))
  File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/gitrepo.py", line 363, in tracked_remote_label
    remote, remote_branch = self.tracked_remote(branch)
  File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/gitrepo.py", line 352, in tracked_remote
    return (self._tracked_remotes[branch]['remote_name'], self._tracked_remotes[branch]['remote_branch'])
KeyError: 'remote_branch'
```

**Comment by uliska** [comment]
When exactly do you get this error? I don't see anything suspicious here.

**Comment by fedelibre** [comment]
When I launch it. The problem is that I checked the commit as "HEAD detached at...".
If I check the commit creating a new branch, like this:

    git checkout -b rewrite-vcs-working c51175d45c82a956cb5d1432efa4b7a4c97a8fb9

then I can launch Frescobaldi.

**Comment by uliska** [comment]
Ah, OK, that means the error isn't related to a *document's*  but to *Frescobaldi's* repository.
That seems to make sense. We try to determine the tracked branch, and probably Git returns something unexpected here. I'm not sure whether this is relevant, although it may be.

**Comment by fedelibre** [comment]
Yes, correct. I guess it's because it finds a weird branch name. Here's an example:

```
$ git checkout e12dd63368651906848f4d5924fe8f23e78a5add
Note: checking out 'e12dd63368651906848f4d5924fe8f23e78a5add'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD si trova ora a e12dd633... (#1015): Really check whether a file is tracked
[frescobaldi ((e12dd633...))]$ 
[frescobaldi ((e12dd633...))]$ 
[frescobaldi ((e12dd633...))]$ 
[frescobaldi ((e12dd633...))]$ 
[frescobaldi ((e12dd633...))]$ git branch
* (HEAD detached at e12dd633)
  goto-line
  master
  rewrite-vcs
  rewrite-vcs-working
```

**Comment by uliska** [comment]
See #1022 for continuing the other issue
