### ISSUE TITLE
'ViewManager' object has no attribute 'connectVcsLabels'

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#1027]
Still trying the latest rewrite-cvs branch. There's a new error I get.
I wonder if this report is useful or should I just use master and wait until you've refactored this branch.

```
Traceback (most recent call last):
  File "frescobaldi", line 11, in <module>
    main.main()                     # Parse command line, create windows etc
  File "/home/fede/src/frescobaldi/frescobaldi_app/main.py", line 267, in main
    win.setCurrentDocument(doc)
  File "/home/fede/src/frescobaldi/frescobaldi_app/mainwindow.py", line 181, in setCurrentDocument
    self.viewManager.setCurrentDocument(doc, findOpenView)
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 320, in setCurrentDocument
    self.activeViewSpace().showDocument(doc)
  File "/home/fede/src/frescobaldi/frescobaldi_app/viewmanager.py", line 159, in showDocument
    view = view_.View(doc)
  File "/home/fede/src/frescobaldi/frescobaldi_app/view.py", line 85, in __init__
    app.viewCreated(self)
  File "/home/fede/src/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/home/fede/src/frescobaldi/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
  File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/manager.py", line 57, in setCurrentDocument
    repo = repo_manager.track_document(vcs_document)
  File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/abstractrepo.py", line 166, in track_document
    self._repos[root_path].track_document(vcs_doc)
  File "/home/fede/src/frescobaldi/frescobaldi_app/vcs/abstractrepo.py", line 133, in track_document
    view.viewSpace().connectVcsLabels(view)
AttributeError: 'ViewManager' object has no attribute 'connectVcsLabels'
```

**Comment by uliska** [comment]
I must admit that I somewhat got stuck recently. I'm unsuccessfully juggling around with determining *and* defining which object knows what about its parent, child and sibling objects, and in what order the information about the properties is determined.

Unfortunately I basically couldn't continue my work since Wednesday, and I'm not sure whether I'll be able to do so in the upcoming week.

**Comment by uliska** [comment]
This seems to be fixed by 9f3f76a8268ac20332e1b59633d6b76e21e33b05.
Could you please confirm @fedelibre?

**Comment by fedelibre** [comment]
Yes, I've pulled the latest changes and now I can launch Frescobaldi without errors.
Thanks!

**Comment by uliska** [comment]
Great. Wen Xin spotted and fixed this one.
