### ISSUE TITLE
frescobaldi flashes up and disappears

### ISSUE THREAD

**Issue by bitwo** [wbsoft/frescobaldi#1050]
I tried repeatedly, tried with different library versions. In the end no version of frescobaldi was running. I freshly installed the actual version of linux  
~ $ uname -a
Linux bb-MS-7713 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
~ $ lsb_release -a
No LSB modules are available.
Distributor ID:    LinuxMint
Description:    Linux Mint 18.3 Sylvia
Release:    18.3
Codename:    sylvia
~ $
I wonder that a "new" version of LinuxMint uses ubuntu 16.04 as a base? 

I set up frescobaldi-3 on another PC successfully I think with Ubuntu 17.04 (Zesty Zapus) succesfully, but cannot figure out what I was doing different.

I installed python3 ... etc again, followed mostly your description https://github.com/wbsoft/frescobaldi/wiki/Running-Frescobaldi-3-From-Source-Git-(Linux)#user-content-workaround-building-python-poppler-qt5-from-source

When I start frescobaldi-3.0.0 the start icon appears and disappears immediatelyafter milliseconds.
I use frescobaldi-2.20, that works. 

May be the developers might extract some information about whats happening with frescobaldi-3.0.0, therefore I add the listings of the terminal: 

~/frescobaldi-3.0.0 $ python3 frescobaldiQApplication: invalid style override passed, ignoring it.
Traceback (most recent call last):
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/plugin.py", line 79, in instance
    return _instances[cls][obj]
  File "/usr/lib/python3.5/weakref.py", line 365, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f99002c8818; to 'type' at 0x19179d8 (PanelManager)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frescobaldi", line 11, in <module>
    main.main()                     # Parse command line, create windows etc
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/main.py", line 247, in main
    win = mainwindow.MainWindow()
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/mainwindow.py", line 128, in __init__
    self.createMenus()
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/mainwindow.py", line 1010, in createMenus
    menu.createMenus(self)
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/menu.py", line 61, in createMenus
    m.addMenu(menu_file(mainwindow))
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/menu.py", line 96, in menu_file
    m.addMenu(snippet.menu.TemplateMenu(mainwindow))
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/snippet/menu.py", line 139, in __init__
    self.addAction(self.tool().actionCollection.templates_manage)
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/snippet/menu.py", line 59, in tool
    return panelmanager.manager(self.mainwindow()).snippettool
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/panelmanager.py", line 36, in manager
    return PanelManager.instance(mainwindow)
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/plugin.py", line 84, in instance
    result.__init__(obj)
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/panelmanager.py", line 51, in __init__
    self.loadPanel("musicview.MusicViewPanel")
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/panelmanager.py", line 86, in loadPanel
    __import__(module_name)
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/musicview/__init__.py", line 63, in <module>
    from qpopplerview import FixedScale, FitWidth, FitHeight, FitBoth
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/qpopplerview/__init__.py", line 91, in <module>
    from .view import View
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/qpopplerview/view.py", line 32, in <module>
    from . import surface
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/qpopplerview/surface.py", line 36, in <module>
    import popplerqt5
RuntimeError: popplerqt5 cannot import type '����' from PyQt5.QtCore
~/frescobaldi-3.0.0 $

May be you what I have done wrong and give me some hint?

The last lines of sudo python3 setup.py install
are
... there are many lines omitted ...
    from .view import View
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/qpopplerview/view.py", line 32, in <module>
    from . import surface
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/qpopplerview/surface.py", line 36, in <module>
    import popplerqt5
RuntimeError: popplerqt5 cannot import type '����' from PyQt5.QtCore
~/frescobaldi-3.0.0 $ 

Regards

**Comment by uliska** [comment]
> I wonder that a "new" version of LinuxMint uses ubuntu 16.04 as a base?

Linux Mint **18** is based on Ubuntu 16.04, see https://linuxmint.com/rel_sylvia.php

I assume this is because a) Ubuntu 16.04 is a Long Time Support release and b) Linux Mint isn't focused on providing the latest sources (anymore).

Linux Mint **19** will be based on Ubuntu 18.04, which also is a Long Time Support release: https://blog.linuxmint.com/?p=3494

**Comment by uliska** [comment]
As Ubuntu 16.04 is still quite widely used and Mint is arguably one of the most popular distributions I will take the chance that I have a spare partition and install Mint 18.3 on it. Maybe I'll see what happens there.

**Comment by uliska** [comment]
> The last lines of sudo python3 setup.py install
are
... there are many lines omitted ...
from .view import View
File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/qpopplerview/view.py", line 32, in
from . import surface
File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/qpopplerview/surface.py", line 36, in
import popplerqt5
RuntimeError: popplerqt5 cannot import type '����' from PyQt5.QtCore
~/frescobaldi-3.0.0 $

@bitwo  Is that correct? It's the same as the end of the output of running Frescobaldi.
