### ISSUE TITLE
PNG capture fails on OSX 10.13.5 with 2.22.0

### ISSUE THREAD

**Issue by andrewbernard** [wbsoft/frescobaldi#1072]
Several users have verified that attempting to use the PNG capture tool in Frescobaldi 2.22.0 on OSX 10.13.5 fails. Error output is consistent across users.

```
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.5/frescobaldi_app/musicview/__init__.py", line 312, in copyImage
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.5/frescobaldi_app/copy2image.py", line 57, in copy_image
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.5/frescobaldi_app/copy2image.py", line 108, in __init__
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.5/frescobaldi_app/copy2image.py", line 150, in readSettings
TypeError: unable to convert a QVariant of type 10 to a QMetaType of type 67
```

**Comment by uliska** [comment]
What is the current state of Frescobaldi 3 on Mac OS?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by andrewbernard** [comment]
I could not get it to run using mac ports. So far, have not investigated further or github build.

**Comment by uliska** [comment]
OK, so it's not an option to simply refer users to the current Frescobaldi version. Unfortunately I have no idea what to do about that issue.

**Comment by dliessi** [comment]
@andrewbernard After we solved the main issues with Frescobaldi 3 on macOS, I updated the frescobaldi-devel port to current master and provided an experimental pre-built application (see https://github.com/wbsoft/frescobaldi/issues/986#issuecomment-414595848).

I cannot reproduce the problem with any of them.
Can you test one of them and report whether the problem is solved?
