### ISSUE TITLE
KeyError when running "Show available fonts" dialog

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#1116]
I'm on master 0bd376 

```
$ python3 -V
Python 3.6.6
```

When I run the "Show available fonts" dialog I get the following error:

```
Traceback (most recent call last):
  File "/home/fede/src/frescobaldi/frescobaldi_app/plugin.py", line 79, in instance
    return _instances[cls][obj]
  File "/usr/lib64/python3.6/weakref.py", line 394, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f87b7d1b638; to 'LilyPondInfo' at 0x7f87b88da828>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fede/src/frescobaldi/frescobaldi_app/engrave/__init__.py", line 309, in showAvailableFonts
    lytools.show_available_fonts(self.mainwindow(), info)
  File "/home/fede/src/frescobaldi/frescobaldi_app/engrave/lytools.py", line 38, in show_available_fonts
    dlg.run_command(info, ['-dshow-available-fonts'], _("Available Fonts"))
  File "/home/fede/src/frescobaldi/frescobaldi_app/engrave/lytools.py", line 59, in run_command
    j = self.job = job.lilypond.LilyPondJob(info)
  File "/home/fede/src/frescobaldi/frescobaldi_app/job/lilypond.py", line 92, in __init__
    self.lilypond_info = docinfo.lilypondinfo()
  File "/home/fede/src/frescobaldi/frescobaldi_app/documentinfo.py", line 243, in lilypondinfo
    version = self.lydocinfo().version()
  File "/home/fede/src/frescobaldi/frescobaldi_app/documentinfo.py", line 138, in lydocinfo
    v = variables.manager(self.document()).variables()
  File "/home/fede/src/frescobaldi/frescobaldi_app/variables.py", line 66, in manager
    return VariableManager.instance(doc)
  File "/home/fede/src/frescobaldi/frescobaldi_app/plugin.py", line 84, in instance
    result.__init__(obj)
  File "/home/fede/src/frescobaldi/frescobaldi_app/variables.py", line 92, in __init__
    self._variables = self.readVariables()
  File "/home/fede/src/frescobaldi/frescobaldi_app/variables.py", line 119, in readVariables
    count = self.document().blockCount()
AttributeError: 'LilyPondInfo' object has no attribute 'blockCount'
```

**Comment by uliska** [comment]
Yes, this is a known issue that I have deliberately accepted.

When reworking the handling of external jobs I would have had to update the "show available fonts" code too. But that would have probably had further complications when merging the code with the currently open "show available fonts" branch. So I decided to accept this broken function for the time until the fonts PR is merged. Sorry.

**Comment by fedelibre** [comment]
Ok, then I'll close it. Hopefully the fonts PR will be merged soon?
