### ISSUE TITLE
Exception: b"PortMidi: `Host error'" when trying to use MIDI port that disappeared (MIDI output)

### ISSUE THREAD

**Issue by jeanas** [wbsoft/frescobaldi#1562]
(Yay, I ran Frescobaldi with #1559 checked out by chance, and could create this bug report using the button :smile:)

```
Traceback (most recent call last):
  File "/home/jean/repos/frescobaldi/frescobaldi_app/miditool/__init__.py", line 64, in slotPlay
    self.widget().play()
  File "/home/jean/repos/frescobaldi/frescobaldi_app/miditool/widget.py", line 155, in play
    self.restart()
  File "/home/jean/repos/frescobaldi/frescobaldi_app/miditool/widget.py", line 172, in restart
    self._player.seek(0)
  File "/home/jean/repos/frescobaldi/frescobaldi_app/midifile/player.py", line 154, in seek
    self.set_position(pos, offset)
  File "/home/jean/repos/frescobaldi/frescobaldi_app/qmidi/player.py", line 85, in set_position
    super(Player, self).set_position(position, offset)
Exception: b"PortMidi: `Host error'"
```

Steps to reproduce:

- Start Fluidsynth (`fluidsynth` in a terminal),
- Set Frescobaldi's MIDI output to the MIDI port created by Fluidsynth in the preferences. Enjoy the MIDI playback,
- Stop fluidsynth (Ctrl-C),
- Try playing any piece in Frescobaldi.

Frescobaldi: 3.2
Extension API: 0.9.0
Python: 3.11.2
Git branch: bugreport
on commit: d97295d4
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.6
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.1.0
python-poppler-qt: 21.3.0
OS: Linux-6.1.15-200.fc37.x86_64-x86_64-with-glibc2.36

**Comment by fedelibre** [comment]
I cannot reproduce this exception in current master.
If I stop fluidsynth, I see the "no output" message in the MIDI player and I cannot hear no sound of course. But there's no exception.

Should we close it?
