### ISSUE TITLE
 Frescobaldi 3.2 not starting (RecursionError: maximum recursion depth exceeded)

### ISSUE THREAD

**Issue by Musicpal** [wbsoft/frescobaldi#1572]
Since some time i am unable to use Frescobaldi, it just does not start anymore.
Thank you so much in advantage.

Messages that appear when started in xterm:
 % frescobaldi 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qpageview/viewactions.py", line 354, in slotZoomFactor
    view.setZoomFactor(factor)
  File "/usr/lib/python3.10/site-packages/qpageview/view.py", line 863, in setZoomFactor
    with self.keepCentered(pos):
  File "/usr/lib64/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.10/site-packages/qpageview/view.py", line 843, in keepCentered
    offset = layout.pos2offset(pos_on_layout)
  File "/usr/lib/python3.10/site-packages/qpageview/layout.py", line 259, in pos2offset
    page = self.pageAt(pos) or self.nearestPageAt(pos)
  File "/usr/lib/python3.10/site-packages/qpageview/layout.py", line 160, in pageAt
    for page in self._pageRects().at(point.x(), point.y()):
  File "/usr/lib/python3.10/site-packages/qpageview/layout.py", line 151, in _pageRects
    r = self._rects = PageRects(self.displayPages())
  File "/usr/lib/python3.10/site-packages/qpageview/rectangles.py", line 64, in __init__
    self.bulk_add(objects)
  File "/usr/lib/python3.10/site-packages/qpageview/rectangles.py", line 92, in bulk_add
    self._items.update((obj, self.get_coords(obj)) for obj in objects)
  File "/usr/lib/python3.10/site-packages/qpageview/rectangles.py", line 92, in <genexpr>
    self._items.update((obj, self.get_coords(obj)) for obj in objects)
RecursionError: maximum recursion depth exceeded
[1]    4916 IOT instruction (core dumped)  frescobaldi

[This is also reported on https://bugzilla.opensuse.org/show_bug.cgi?id=1209802]

**Comment by Musicpal** [comment]
Thank you very much for your quick response!
Removing frescobaldi.conf was indeed the solution.

Frescobaldi.conf is 11930 lines long, see if i can copy it here:
Get a no from github here,  65536 characters is the max.

Also for pastebin it is to much.
If you still want it please let me know.
Kindly,

Peter

**Comment by Musicpal** [comment]
[frescobaldi.conf.tar.gz](https://github.com/frescobaldi/frescobaldi/files/11083583/frescobaldi.conf.tar.gz)

Does not take tar.xz but tar.gz seems to work.
Thank you so much!
Thanks to people like you i have a working Frescobaldi application.

**Comment by Musicpal** [comment]
Sorry for that, this one should work.
[frescobaldi.conf.tar.gz](https://github.com/frescobaldi/frescobaldi/files/11083643/frescobaldi.conf.tar.gz)
