### ISSUE TITLE
macOS: "Object Editor" tool causes internal error

### ISSUE THREAD

**Issue by jeanas** [wbsoft/frescobaldi#1677]
This was reported by Artur Dobija on the LilyPond Facebook group (https://www.facebook.com/groups/gnulilypond).

I was able to reproduce it on Linux by applying the following diff:

```diff
diff --git a/frescobaldi_app/svgview/__init__.py b/frescobaldi_app/svgview/__init__.py
index b2609ed3..7030f4ac 100644
--- a/frescobaldi_app/svgview/__init__.py
+++ b/frescobaldi_app/svgview/__init__.py
@@ -56,7 +56,7 @@ class SvgViewPanel(panel.Panel):
         self.toggleViewAction().setText(_("SV&G View"))
 
     def createWidget(self):
-        if not importlib.util.find_spec('PyQt5.QtWebEngineWidgets'):
+        if True: #not importlib.util.find_spec('PyQt5.QtWebEngineWidgets'):
             import webenginedummy
             return webenginedummy.WebEngineDummy(self)
         from . import widget
@@ -91,5 +91,3 @@ class Actions(actioncollection.ActionCollection):
         self.svg_zoom_in.setText(_("Zoom &In"))
         self.svg_zoom_out.setText(_("Zoom &Out"))
         self.svg_zoom_original.setText(_("Original &Size"))
-
-
```

This removes the use of QtWebEngine to emulate what happens on macOS with the app bundle, where it's not shipped due to https://github.com/frescobaldi/frescobaldi/issues/1244.

After applying this, opening Tools > Coding > Object Editor gives

```
Traceback (most recent call last):
  File "/home/jean/repos/frescobaldi/frescobaldi_app/objecteditor/widget.py", line 130, in showEvent
    self.connectToSvgView()
  File "/home/jean/repos/frescobaldi/frescobaldi_app/objecteditor/widget.py", line 99, in connectToSvgView
    self.svgview.objectStartDragging.connect(self.startDragging)
    ^^^^^^^^^^^^
AttributeError: 'Widget' object has no attribute 'svgview'
Traceback (most recent call last):
  File "/home/jean/repos/frescobaldi/frescobaldi_app/panel.py", line 81, in showEvent
    self.widget()
  File "/home/jean/repos/frescobaldi/frescobaldi_app/panel.py", line 71, in widget
    w = self.createWidget()
        ^^^^^^^^^^^^^^^^^^^
  File "/home/jean/repos/frescobaldi/frescobaldi_app/objecteditor/__init__.py", line 47, in createWidget
    w = widget.Widget(self)
        ^^^^^^^^^^^^^^^^^^^
  File "/home/jean/repos/frescobaldi/frescobaldi_app/objecteditor/widget.py", line 55, in __init__
    self.svgview = panelmanager.manager(tool.mainwindow()).svgview.widget().view
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebEngineDummy' object has no attribute 'view'
```

For this user, the error actually wasn't shown due to https://github.com/frescobaldi/frescobaldi/issues/1676

**Comment by fedelibre** [comment]
> This removes the use of QtWebEngine to emulate what happens on macOS with the app bundle, where it's not shipped due to [#1244](https://github.com/frescobaldi/frescobaldi/issues/1244).

QtWebEngine is now present on macOS packages  so we can close this issue.
