### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#369]
As most of the code is already written in Python 3 style, it should be possible to supoort Python3 fully without breaking compatibility with python 2.

Although the Python developers do not recommend that you try to support py2 and 3 from within one codebase, I think we should do it for a transitional period of 1 or 2 years.

Porting to Qt5 will be done much later, and at that time we could decide to drop py2 support.

**Comment by wbsoft** [comment]
I encourage everybody to check Frescobaldi running under python3 (just python3 frescobaldi on the command line). You should also compile `python-poppler-qt4` under python3, and of course install PyQt4 for python3. Please report issues here. Currently basic stuff works nicely!

**Comment by PeterBjuhr** [comment]
I managed to setup everything for python3 debugging, I hope.

But got the following error:

	Traceback (most recent call last):
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/panel.py", line 78, in showEvent
	    self.widget()
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/panel.py", line 72, in widget
	    w = self.createWidget()
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/quickinsert/__init__.py", line 51, in createWidget
	    import widget
	ImportError: No module named 'widget'
	Traceback (most recent call last):
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/panel.py", line 78, in showEvent
	    self.widget()
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/panel.py", line 72, in widget
	    w = self.createWidget()
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/svgview/__init__.py", line 57, in createWidget
	    import widget
	ImportError: No module named 'widget'

Does that mean that the `svgview` and `quickinsert` widgets aren't working under Python3 (can't import `widget`??) or that my setup was unsuccessful?

**Comment by PeterBjuhr** [comment]
If I'm correct it's the change in relative import (between python2 and python3) that causes this!

**Comment by wbsoft** [comment]
Indeed, we must use from . import for modules inside packages.

**Comment by PeterBjuhr** [comment]
Another issue in `svgview/widget.initSvg`. On row 108 we have:

    if files:

In python2 this is `False` and in python3 `True` (which eventually leads to an error).

`files` is defined by:

    files = svgfiles.SvgFiles.instance(doc)

Please take a look!

**Comment by PeterBjuhr** [comment]
Thanks!

**Comment by PeterBjuhr** [comment]
When debugging #566 I also got another error:

	Traceback (most recent call last):
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/miditool/widget.py", line 224, in loadResults
	    self.loadSong(files.current)
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/miditool/widget.py", line 228, in loadSong
	    self._player.set_song(files.song(index))
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/miditool/midifiles.py", line 67, in song
	    song = self._songs[index] = midifile.song.load(self._files[index])
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/midifile/song.py", line 42, in load
	    return Song(div, tracks)
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/midifile/song.py", line 215, in __init__
	    self.events = events_dict(tracks)
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/midifile/song.py", line 54, in events_dict
	    parser.parse_midi_events(track)):
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/midifile/parser.py", line 192, in time_events_grouped
	    for delta, ev in track:
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/midifile/parser.py", line 112, in parse_midi_events
	    delta, pos = read_var_len(s, pos)
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/midifile/parser.py", line 86, in read_var_len
	    i = ord(s[pos])
	TypeError: ord() expected string of length 1, but int found

**Comment by PeterBjuhr** [comment]
When closing the app I also got this:

    python3: malloc.c:3987: _int_free: Assertion `p->bk_nextsize->fd_nextsize == p' failed.

**Comment by wbsoft** [comment]
Yes, will fix midi.

**Comment by wbsoft** [comment]
now the midi player works in python3. It automatically uses the portmidi ctypes implementation, which works well on my system. please test the midi input.

**Comment by PeterBjuhr** [comment]
Great!

**Comment by PeterBjuhr** [comment]
Python3 error in MusicXML export:

	Traceback (most recent call last):
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/file_export/__init__.py", line 65, in exportMusicXML
	    xml.write(filename)
	  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/ly/musicxml/create_musicxml.py", line 567, in write
	    self.tree.write(f, encoding=encoding, xml_declaration=False)
	  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 778, in write
	    short_empty_elements=short_empty_elements)
	  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
	    next(self.gen)
	  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 837, in _get_writer
	    yield file.write
	  File "/usr/lib/python3.4/contextlib.py", line 336, in __exit__
	    raise exc_details[1]
	  File "/usr/lib/python3.4/contextlib.py", line 321, in __exit__
	    if cb(*exc_details):
	  File "/usr/lib/python3.4/contextlib.py", line 267, in _exit_wrapper
	    callback(*args, **kwds)
	TypeError: must be str, not bytes

**Comment by PeterBjuhr** [comment]
In python3 the encoding is required to be "unicode". In python2 this will cause an error:

    LookupError: unknown encoding: unicode

Can this be solved with a from future import?

**Comment by PeterBjuhr** [comment]
To clarify: the difference is in `xml.etree.ElementTree.ElementTree.write`. See:

https://docs.python.org/3.4/library/xml.etree.elementtree.html#xml.etree.ElementTree.ElementTree.write

https://docs.python.org/2.7/library/xml.etree.elementtree.html#xml.etree.ElementTree.ElementTree.write

**Comment by PeterBjuhr** [comment]
> Can this be solved with a from future import?

Sorry, I haven't focused on the python2 -> python3 issue. It seems that the `future` module includes only a limited sets of features from python3.

**Comment by proski** [comment]
I fixed MusicXML export in 6d9de68657399734cfb80e0e0457f029765b3206. Yes, we did the impossible and we have a pretty good support for Python 2 and 3 in the same codebase. Let's make this bug a metabug depending on existing bugs concerned with Python 3 support.

I thing we can add Python 3 to the trove categories in setup.py. I tested Python 3.2 and 3.4, so I assume Python 3.3 should be supported as well.

**Comment by proski** [comment]
Dependencies between issues are not supported yet (https://github.com/isaacs/github/issues/210), so let's do it manually:

Issue #577
Issue #596

Anything else?

**Comment by wbsoft** [comment]
We could make python 3 support a milestone, then we can track how far we are. Shall I do that?

**Comment by PeterBjuhr** [comment]
It sounds like a good idea to me!

**Comment by wbsoft** [comment]
I think we can close this issue?
