### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'insert'

### ISSUE THREAD

**Issue by scottlinux** [wbsoft/frescobaldi#543]
Frescobaldi 2.18-dev Git 2014122901

If I edit a file, and click engrave before saving, a traceback occurs.

If I save first, then engrave, no traceback occurs.

Traceback (most recent call last):
  File "/home/smiller/Downloads/frescobaldi/frescobaldi_app/engrave/__init__.py", line 125, in engraveRunner
    self.engravePreview()
  File "/home/smiller/Downloads/frescobaldi/frescobaldi_app/engrave/__init__.py", line 129, in engravePreview
    self.engrave('preview')
  File "/home/smiller/Downloads/frescobaldi/frescobaldi_app/engrave/__init__.py", line 180, in engrave
    self.runJob(command.defaultJob(doc, args), doc)
  File "/home/smiller/Downloads/frescobaldi/frescobaldi_app/engrave/command.py", line 53, in defaultJob
    filename, includepath = documentinfo.info(document).jobinfo(True)
  File "/home/smiller/Downloads/frescobaldi/frescobaldi_app/documentinfo.py", line 208, in jobinfo
    includepath.insert(0, os.path.dirname(filename))
AttributeError: 'unicode' object has no attribute 'insert'

python: 2.7.9 
qt: 4.8.6
pyqt4: 4.11.2
sip: 4.16.4
Debian Jessie 3.16.0-4-amd64

Sample file: http://fpaste.org/164081/

**Comment by wbsoft** [comment]
According to other user, problem still persists in 2.17.1

**Comment by wbsoft** [comment]
Sorry, I fixed it after 2.17.1, so next release will contain the fix.
