### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/var/folders/3_/fhptxgks4vd0t5spsm5mbjd80000gn/T/frescobaldi-2BJezG/tmpBmiAYU'

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#554]
Frescobaldi: 2.17.1

Python: 2.7.9 -- Qt: 4.8.6 -- PyQt4: 4.11.3 -- sip: 4.16.5
OS: Darwin-14.0.0-x86_64-i386-64bit
```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/__init__.py", line 125, in engraveRunner
    self.engravePreview()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/__init__.py", line 129, in engravePreview
    self.engrave('preview')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/__init__.py", line 180, in engrave
    self.runJob(command.defaultJob(doc, args), doc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/command.py", line 53, in defaultJob
    filename, includepath = documentinfo.info(document).jobinfo(True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/documentinfo.py", line 206, in jobinfo
    scratch.saveDocument()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/scratchdir.py", line 65, in saveDocument
    self.create()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/scratchdir.py", line 46, in create
    self._directory = util.tempdir()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/util.py", line 108, in tempdir
    return tempfile.mkdtemp(dir=_tempdir)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 333, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/var/folders/3_/fhptxgks4vd0t5spsm5mbjd80000gn/T/frescobaldi-2BJezG/tmpBmiAYU'
```
Optionally describe below what you were doing:

I had just pasted some LilyPond code into a new blank frescobaldi window, made a few modifications, and then clicked on the “Engrave” button.  I did an ls -al /var/folders/3_/fhptxgks4vd0t5spsm5mbjd80000gn/T:

(...)

Sure enough, no frescobaldi-2BJezG/tmpBmiAYU there.  I also did:    
```
sudo find /var -name fresco\* -print | more  
```
no such directories were found.

If I click the Engrave button again, a similar error occurs, but with a different directory name.

I then got a new blank window and entered:  {c4 c c c } 
and then I clicked on the Engrave button, with the following results:

```
Traceback (most recent call last):
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/__init__.py", line 125, in engraveRunner
self.engravePreview()
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/__init__.py", line 129, in engravePreview
self.engrave('preview')
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/__init__.py", line 180, in engrave
self.runJob(command.defaultJob(doc, args), doc)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/command.py", line 53, in defaultJob
filename, includepath = documentinfo.info(document).jobinfo(True)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/documentinfo.py", line 206, in jobinfo
scratch.saveDocument()
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/scratchdir.py", line 65, in saveDocument
self.create()
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/scratchdir.py", line 46, in create
self._directory = util.tempdir()
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/util.py", line 108, in tempdir
return tempfile.mkdtemp(dir=_tempdir)
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 333, in mkdtemp
_os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/var/folders/3_/fhptxgks4vd0t5spsm5mbjd80000gn/T/frescobaldi-2BJezG/tmp0bjg5V'
```
It would appear that this functionality is no longer working.

**Comment by wbsoft** [comment]
It seems creating a temp dir inside a (global) tempdir is not working. It looks like the global temp dir is not existing at all (but its existence should be tested while Frescobaldi is running; on exit the global tempdir will be erased anyway, see `util.tempdir()`).

**Comment by dliessi** [comment]
I don't know why this happens: I never had this problem on the systems I tested (including Darwin 14, i.e. Yosemite).

**Comment by dliessi** [comment]
@wbsoft What are we going to do with this issue?
Examining the code, I believe this is not a bug in Frescobaldi, nor in Frescobaldi's packaging.
I couldn't reproduce the problem and no other Mac user reported it, even though it should happen every time they compile a score without saving it, which in my experience is quite a frequent event.
I'd say that this was a temporary glitch or a problem with the user's setup.
It would help if the user could tell us if this happened only once or it happens usually.

**Comment by wbsoft** [comment]
I have asked the reporter whether this happens everytime or just once. When it does not happen anymore, let's close this bug.

**Comment by dliessi** [comment]
@wbsoft Have you heard from the reporter?
I believe this was a temporary glitch and surely not a problem in Frescobadi, so I think we can close the issue.

**Comment by wbsoft** [comment]
maybe a disk full issue, I never heard back.
