### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by leyoyel** [wbsoft/frescobaldi#574]
Hi, 
first thank you for your work and have a beautiful year.
I'm on KxStudio (KUbuntu for music)
When I try to open Frescobaldi in a terminal here's what it say:

Traceback (most recent call last):
  File "/usr/bin/frescobaldi", line 3, in <module>
    import frescobaldi_app.main
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/main.py", line 114, in <module>
    startmain()
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/main.py", line 82, in startmain
    win = mainwindow.MainWindow()
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/mainwindow.py", line 109, in __init__
    self.createMenus()
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/mainwindow.py", line 761, in createMenus
    menu.createMenus(self)
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/menu.py", line 65, in createMenus
    m.addMenu(f(mainwindow))
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/menu.py", line 95, in menu_file
    m.addAction(panels.manager(mainwindow).snippettool.actionCollection.file_save_as_template)
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/panels.py", line 40, in manager
    return PanelManager.instance(mainwindow)
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/plugin.py", line 85, in instance
    result.__init__(obj)
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/panels.py", line 48, in __init__
    import musicview
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/musicview/__init__.py", line 53, in <module>
    from . import documents
  File "/usr/lib/python2.7/dist-packages/frescobaldi_app/musicview/documents.py", line 33, in <module>
    import popplerqt4
RuntimeError: the sip module implements API v11.0 but the popplerqt4 module requires API v8.1

It seems there is a problem with the version of poppler api ?
What can i do ?

thanks for your replie

**Comment by wbsoft** [comment]
The kubuntu packagers probably forgot to recompile python-poppler-qt4 with the correct sip version. Please report this problem there.
