### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#597]
Reported by a user :

Frescobaldi: 2.17.2

Python: 2.7.9 -- Qt: 4.8.6 -- PyQt4: 4.11.3 -- sip: 4.16.5
OS: Darwin-14.0.0-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/mainwindow.py", line 927, in slotRecentFilesAction
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/mainwindow.py", line 373, in openUrl
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/app.py", line 84, in openUrl
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/document.py", line 73, in new_from_url
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/document.py", line 60, in load_data
IOError: [Errno 2] No such file or directory: u'/Users/michaelhendry/includes/common.ly'

Optionally describe below what you were doing:

I was moving commonly used code into an include file (common.ly).

I moved the file from its original location, and when I tried to re-open it from the MRU list, I generated this set of error messages.

My fault! But the IOError could have been detected and reflected back to me.

**Comment by proski** [comment]
I tried this functionality. I moved a recent file away and it disappeared from the list. Then I moved it back, and now I'm getting a traceback:

Traceback (most recent call last):
  File "/home/proski/src/frescobaldi/frescobaldi_app/mainwindow.py", line 926, in populateRecentFilesMenu
    for url in recentfiles.urls():
  File "/home/proski/src/frescobaldi/frescobaldi_app/recentfiles.py", line 61, in urls
    load()
  File "/home/proski/src/frescobaldi/frescobaldi_app/recentfiles.py", line 51, in load
    for url in urls:
TypeError: 'QUrl' object is not iterable

The code doing the iterations is not new. No idea why it's breaking now.

**Comment by proski** [comment]
If turns out my ~/.config/frescobaldi/frescobaldi.conf starts with:

[General]
settings_version=1
autocomplete=true
recent_files=@Invalid()

**Comment by wbsoft** [comment]
that happens when an empty list is stored. When requesting it with QUrl as the preferred type and an empty list as default value, a single QUrl is returned. I consider this a problem inside PyQt4 but I work around it in `qsettings.py` for strings, and now will add a similar method to safely get a list or urls. Please test it as soon as I commit :-)

**Comment by proski** [comment]
It's fixed now, thank you!
