### ISSUE TITLE
error importing slexer

### ISSUE THREAD

**Issue by igneus** [wbsoft/frescobaldi#612]
I use the current development version (from branch master) of Frescobaldi. Today I noticed that opening the Snippets panel leads to a crash

```
Traceback (most recent call last):
  File "/home/igneus/apps/frescobaldi/frescobaldi_app/panel.py", line 82, in showEvent
    self.widget()
  File "/home/igneus/apps/frescobaldi/frescobaldi_app/panel.py", line 72, in widget
    w = self.createWidget()
  File "/home/igneus/apps/frescobaldi/frescobaldi_app/snippet/tool.py", line 61, in createWidget
    from . import widget
  File "/home/igneus/apps/frescobaldi/frescobaldi_app/snippet/widget.py", line 39, in <module>
    from . import edit
  File "/home/igneus/apps/frescobaldi/frescobaldi_app/snippet/edit.py", line 47, in <module>
    from . import highlight
  File "/home/igneus/apps/frescobaldi/frescobaldi_app/snippet/highlight.py", line 37, in <module>
    from ly import slexer
ImportError: cannot import name slexer
```

I obtained python-ly (checked out current development version, set PYTHONPATH accordingly), but the error still occurs. I debugged if it could be a library path problem, but it is not: printed out at the end of main.py, sys.path contains the directory where i have the ly module.
However, if I at the very same place "from ly import slexer", the import crashes in a similar way as copied above.

Finally I realized there still is a ly subdirectory in the frescobaldi source. So there seems to be a module name clash - the external ly, where slexer is, cannot be imported, because there is another ly (without slexer) in the frescobaldi directory tree.

**Comment by wbsoft** [comment]
Yes, you should remove the stale ly folder (see ChangeLog, this will also be announced when 2.18 is released).
