### ISSUE TITLE
MusicXML export traceback: ValueError: '0.25' is not in list

### ISSUE THREAD

**Issue by scottlinux** [wbsoft/frescobaldi#630]
Latest frescobaldi 2.18 and python-ly 0.9 from git (1 Mar 2015)
Linux, Debian Jessie, python2.7

File > Export MusicXML results in a traceback.

Let me know if the sample file is needed.

<pre>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/frescobaldi-2.18-py2.7.egg/frescobaldi_app/file_export/__init__.py", line 65, in exportMusicXML
    writer.parse_tree(documentinfo.music(doc))
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/lymus2musxml.py", line 92, in parse_tree
    self.parse_nodes(mus_nodes)
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/lymus2musxml.py", line 104, in parse_nodes
    func_call(m)
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/lymus2musxml.py", line 226, in Note
    self.mediator.set_tremolo(trem_type='start', repeats=self.trem_rep)
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/ly2xml_mediator.py", line 580, in set_tremolo
    bs, durtype = calc_trem_dur(repeats, self.current_note.duration, duration)
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/ly2xml_mediator.py", line 836, in calc_trem_dur
    new_type = xml_objs.durval2type(str(duration/repeats))
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/xml_objs.py", line 695, in durval2type
    return xml_types[ly.duration.durations.index(str(durval))]
ValueError: '0.25' is not in list
</pre>

**Comment by PeterBjuhr** [comment]
Thanks for the report! I'll look into it shortly.

**Comment by scottlinux** [comment]
Thank you! I just tried this change, and I've got another traceback. I may be doing something odd with tremolos perhaps?

This is the file (piece in progress): http://fpaste.org/192059/

<pre>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/frescobaldi-2.18-py2.7.egg/frescobaldi_app/file_export/__init__.py", line 65, in exportMusicXML
    writer.parse_tree(documentinfo.music(doc))
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/lymus2musxml.py", line 93, in parse_tree
    self.parse_nodes(mus_nodes)
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/lymus2musxml.py", line 105, in parse_nodes
    func_call(m)
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/lymus2musxml.py", line 249, in Duration
    self.mediator.set_tremolo(trem_type='start', repeats=self.trem_rep)
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/ly2xml_mediator.py", line 581, in set_tremolo
    bs, durtype = calc_trem_dur(repeats, self.current_note.duration, duration)
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/ly2xml_mediator.py", line 841, in calc_trem_dur
    new_type = xml_objs.durval2type(str(duration // repeats))
  File "/usr/local/lib/python2.7/dist-packages/python_ly-0.9-py2.7.egg/ly/musicxml/xml_objs.py", line 695, in durval2type
    return xml_types[ly.duration.durations.index(str(durval))]
ValueError: '0' is not in list
</pre>

**Comment by PeterBjuhr** [comment]
Thanks for the file!

I think I found the loophole now. And was able to export your file without errors. But like your piece the export function is "in progress" so that doesn't mean that you'll get a perfect xml-file.

I'll close this issue now, but I will take a closer look at your file and hopefully make some more improvements!
