### ISSUE TITLE
MusicXML import with umlauts in the file path or name

### ISSUE THREAD

**Issue by tobik** [wbsoft/frescobaldi#662]
I get a error when import MusicXML files with umlauts in the file name or path.

Traceback (most recent call last):
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\view.py", line 164, in dropEvent
    self.window().dropEvent(ev)
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\mainwindow.py", line 282, in dropEvent
    imp.openDialog()
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\__init__.py", line 86, in openDialog
    self.openMusicxmlDialog()
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\__init__.py", line 111, in openMusicxmlDialog
    self.runImport()
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\__init__.py", line 161, in runImport
    stdout, stderr = dlg.run_command()
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\toly_dialog.py", line 156, in run_command
    stderr = subprocess.PIPE)
  File "c:\Python27\lib\subprocess.py", line 672, in __init__
  File "c:\Python27\lib\subprocess.py", line 882, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 238: ordinal not in range(128)

**Comment by proski** [comment]
I cannot reproduce the problem with the current Frescobaldi. What is the version of Frescobaldi? If it's older than 2.18, please try 2.18. What is the version of Python? What is is the exact file name?

**Comment by tobik** [comment]
Frescobaldi version is 2.18.
The file name is "11ä.xml". But the same happens with umlauts in the path name.
I have various versions of python installed. In the path is Python 3.4.1. Which one is Frescobaldi using?

**Comment by PeterBjuhr** [comment]
It's quite clear that it is 2.18 you are using, because you're using the updated importer.

Also, I'm no expert on Python on Windows but doesn't the path `c:\Python27\lib\subprocess.py` imply that it's Python 2.7?

To be sure you can goto Help->About Frescobaldi->version and get all the data about your setup.

**Comment by tobik** [comment]
Installed are Python 2.7.9 and Python 3.4.1. 
Additional Pythons exists in LibreOffice (3.3.3), Inkscape (3.4.1) and LilyPond (2.4.5).
The mentioned file c:\Python27\lib\subprocess.py does not exists at all. I have no idea where it is from.

Frescobaldi: 2.18
Python: 2.7.1
Qt: 4.7.2
PyQt4: 4.8.4
sip: 4.12.2
python-ly: 0.9
poppler: unknown
python-poppler-qt4: unknown
Operating System:
Windows-post2008Server-6.2.9200

**Comment by dliessi** [comment]
> The mentioned file `c:\Python27\lib\subprocess.py` does not exists at all.

It existed on the machine where the pre-compiled binary was created (there is a hint about @wbsoft's folder structure [here](https://github.com/wbsoft/frescobaldi/blob/master/windows/freeze.py#L7)).
Pre-built binaries don't use the Python installed in the system, but include their own version.

**Comment by PeterBjuhr** [comment]
I can confirm this error on Windows7.

**Comment by proski** [comment]
I also confirm it with the current code and Python 3.4.2 on Windows 7. While at that, I have fixed the missing "import util".

**Comment by tobik** [comment]
This issue remains open in 1.18.2. 

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\view.py", line 164, in dropEvent
    self.window().dropEvent(ev)
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\mainwindow.py", line 291, in dropEvent
    imp.openDialog(i)
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\__init__.py", line 83, in openDialog
    self.openMusicxmlDialog()
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\__init__.py", line 108, in openMusicxmlDialog
    self.runImport()
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\__init__.py", line 158, in runImport
    stdout, stderr = dlg.run_command()
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\toly_dialog.py", line 173, in run_command
    stderr = subprocess.PIPE)
  File "c:\Python27\lib\subprocess.py", line 672, in __init__
    raise ValueError("startupinfo is only supported on Windows "
  File "c:\Python27\lib\subprocess.py", line 882, in _execute_child
    return _subprocess.DuplicateHandle(_subprocess.GetCurrentProcess(),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 228: ordinal not in range(128)
```

**Comment by tobik** [comment]
http://stackoverflow.com/questions/1910275/unicode-filenames-on-windows-with-python-subprocess-popen

**Comment by fedelibre** [comment]
Testing Frescobaldi 3.3.0 on Windows 10.

File `11ä.ly`:

```
\version "2.24.1"

{ c'1 }
```

Run LilyPond>Engrave custom>XML to get the 11ä.xml file.

Then close the active document and try to import the XML file.

I get this error:

![Schermata del 2023-04-05 12-06-43](https://user-images.githubusercontent.com/1644647/230051895-98024799-b63a-4bbb-a3b4-b1783db3915f.png)

Where is the log file?!?

**Comment by fedelibre** [comment]
Yes, there's a problem with detecting python.exe @19joho66 

Other features are not available, for example convert-ly:
![Schermata del 2023-04-05 13-06-57](https://user-images.githubusercontent.com/1644647/230064892-05da79d3-6588-4d6b-9610-efa192de313f.png)


I tried launching Frescobaldi from the command prompt to get some debug information, but no message is printed.

If I try to use the `--help` option, it fails with the following error:

![Schermata del 2023-04-05 12-59-22](https://user-images.githubusercontent.com/1644647/230063565-287c4ff0-5e7e-4625-996d-da4927e42443.png)

**Comment by fedelibre** [comment]
I might install Python 3.10 and let it add to the PATH. But I guess it should be included in Frescobaldi installer? The python3*.dll files here maybe?

```
C:\Program Files (x86)\Frescobaldi>dir
 Il volume nell'unità C è C drive
 Numero di serie del volume: CC86-5CBA

 Directory di C:\Program Files (x86)\Frescobaldi

05/04/2023  09:47    <DIR>          .
05/04/2023  09:47    <DIR>          ..
07/12/2019  11:09            12.088 api-ms-win-crt-heap-l1-1-0.dll
07/12/2019  11:09            11.784 api-ms-win-crt-locale-l1-1-0.dll
07/12/2019  11:09            21.816 api-ms-win-crt-math-l1-1-0.dll
07/12/2019  11:09            15.672 api-ms-win-crt-runtime-l1-1-0.dll
07/12/2019  11:09            17.208 api-ms-win-crt-stdio-l1-1-0.dll
04/04/2023  20:13           566.272 freetype.dll
04/04/2023  20:12            24.064 frescobaldi.exe
05/04/2023  09:46    <DIR>          iconengines
05/04/2023  09:46    <DIR>          imageformats
05/04/2023  09:47    <DIR>          lib
05/04/2023  09:46    <DIR>          platforms
05/04/2023  09:46    <DIR>          printsupport
23/03/2022  23:22            61.904 python3.dll
23/03/2022  23:22         4.124.112 python310.dll
05/04/2023  09:47           710.501 unins000.dat
05/04/2023  09:45         2.563.425 unins000.exe
23/03/2022  23:22            76.152 vcruntime140.dll
              12 File      8.204.998 byte
               7 Directory  13.230.190.592 byte disponibili
```

BTW, vcruntime140.dll is present. See above screenshot...

**Comment by 19joho66** [comment]
I've set up a virtual machine with a fresh win10 installation. There I saw that the dlls are not ok yet. I've build another setup which hopefully fixes that. Maybe you could try that one an see if it resolves some of the problems.
I'll send you the link via EMail

**Comment by fedelibre** [comment]
Now I get a different error:

![Schermata del 2023-04-05 15-31-03](https://user-images.githubusercontent.com/1644647/230097907-3cf5f74b-3fdd-42bb-9ac4-b4042f15ed67.png)

**Comment by 19joho66** [comment]
It looks like it has something to do with the way the new Lilypond is installed. With Lilypond 2.18 it works fine
![image](https://user-images.githubusercontent.com/15361970/230109303-a2ac6af4-5b66-490c-8dd2-408ca971d7d0.png)

**Comment by fedelibre** [comment]
Sorry, multitasking... Where did you see the special characters?

**Comment by fedelibre** [comment]
Ah, Ok. We are mixing things, sorry. If you look at above screenshots, you see that I made tests on unsaved files. So no problem of special characters in the file name. I should have opened a new issue.

It seems to be caused by the removing of lilypond-windows.exe maybe?
Or it's just python.exe which cannot be found?

**Comment by 19joho66** [comment]
This problem occurs on a clean win10 install because the dlls from the VC2019 redistributional package are missing. I've now build a setup that will automatically install the package if it is missing. This works on my clean virtual machine.
I'll send the link to the setup via email.

**Comment by fedelibre** [comment]
Thanks, I've installed the latest version in another machine. Now convert-ly works fine.

Back to the issue discussed here. Yesterday I was using a Linux machine and a Windows virtual machine. I think I did the ly to xml conversion in Linux and it worked fine. Now I'm on a Windows laptop and the conversion ly to xml is failing:

```
lilypond.exe 2.24.1 [11ä.ly] in avvio...
warning: no such internal option: xml-export
programming error: file name not normalized: C:\Program Files (x86)\Frescobaldi\lib\ly\xml\xml-export-init.ly
continuing, cross fingers
Processing `C:/Users/test/Documents/11ä.ly'
Parsing...
programming error: file name not normalized: C:\Program Files (x86)\Frescobaldi\lib\ly\xml\xml-export-init.ly
continuing, cross fingers
Writing XML to standard output...
Interpreting music...
Preprocessing graphical objects...
Finding the ideal number of pages...
Fitting music on 1 page...
Drawing systems...
Converting to `11ä.pdf'...
Writing XML completed.Omitting the destination on a call to format is deprecated.
Pass #f as the destination, before the format string.
<?xml version="1.0" encoding="utf-8"?>
<document/>

Success: compilation successfully completed
Completato con successo in 2.3".
```

**Comment by fedelibre** [comment]
I've just tested it again on Frescobaldi 4.0.1 (Windows) and LilyPond 2.24.4. Same error:

<code>
Starting lilypond.exe 2.24.4 [11ä.ly]...
warning: no such internal option: xml-export
programming error: file name not normalized: C:\Users\test\AppData\Local\Programs\Frescobaldi\app_packages\ly\xml\xml-export-init.ly
continuing, cross fingers
Processing `C:/Users/test/Documents/11ä.ly'
Parsing...
programming error: file name not normalized: C:\Users\test\AppData\Local\Programs\Frescobaldi\app_packages\ly\xml\xml-export-init.ly
continuing, cross fingers
Writing XML to standard output...
Interpreting music...
Preprocessing graphical objects...
Finding the ideal number of pages...
Fitting music on 1 page...
Drawing systems...
Converting to `11ä.pdf'...
Writing XML completed.
<?xml version="1.0" encoding="utf-8"?>
<document/>
Omitting the destination on a call to format is deprecated.
Pass #f as the destination, before the format string.

Success: compilation successfully completed
Completed successfully in 2.5".
</code>

**Comment by fedelibre** [comment]
LilyPond version 2.25.5 logs are more verbose and precise:

<code>
Starting lilypond.exe 2.25.25 [11ä.ly]...
warning: no such program option: xml-export
programming error: file name not normalized: C:\Users\test\AppData\Local\Programs\Frescobaldi\app_packages\ly\xml\xml-export-init.ly
continuing, cross fingers
Processing `C:/Users/test/Documents/11ä.ly'
Parsing...
programming error: file name not normalized: C:\Users\test\AppData\Local\Programs\Frescobaldi\app_packages\ly\xml\xml-export-init.ly
continuing, cross fingers
[C:/Users/test/AppData/Local/Programs/Frescobaldi/app_packages/ly/xml/xml-export-init.ly:31:2](https://github.com/frescobaldi/frescobaldi/issues/0): error: Guile signaled an error for the expression beginning here
#
 (begin
In procedure symbol->string: Wrong type argument in position 1 (expecting symbol): "-"
[C:/Users/test/AppData/Local/Programs/Frescobaldi/app_packages/ly/xml/xml-export-init.ly:47:2](https://github.com/frescobaldi/frescobaldi/issues/1): error: Guile signaled an error for the expression beginning here
#
 (xml-outputter 'declaration)
Wrong type to apply: #f
[C:/Users/test/AppData/Local/Programs/Frescobaldi/app_packages/ly/xml/xml-export-init.ly:48:2](https://github.com/frescobaldi/frescobaldi/issues/2): error: Guile signaled an error for the expression beginning here
#
 (xml-outputter 'open-tag 'document)
Wrong type to apply: #f

Note: compilation failed and \version outdated, did you
update input syntax with convert-ly?

  https://lilypond.org/doc/v2.25/Documentation/usage/updating-files-with-convert_002dly

Interpreting music...
Preprocessing graphical objects...
Finding the ideal number of pages...
Fitting music on 1 page...
Drawing systems...
Converting to `11ä.pdf'...
[C:/Users/test/AppData/Local/Programs/Frescobaldi/app_packages/ly/xml/xml-export-init.ly:53:2](https://github.com/frescobaldi/frescobaldi/issues/3): error: Guile signaled an error for the expression beginning here
#
 (xml-outputter 'close-tag)
Wrong type to apply: #f
Exited with return code 1.
</code>
