### ISSUE TITLE
Python 3, Windows, convert-ly: environment can only contain strings

### ISSUE THREAD

**Issue by proski** [wbsoft/frescobaldi#665]
Traceback (most recent call last):
      File "C:\python\src\frescobaldi\frescobaldi_app\documentactions.py", line 131, in convertLy
        convert_ly.convert(self.mainwindow())
      File "C:\python\src\frescobaldi\frescobaldi_app\convert_ly.py", line 56, in convert
        dlg.run()
      File "C:\python\src\frescobaldi\frescobaldi_app\convert_ly.py", line 245, in run
        stderr = subprocess.PIPE)
      File "C:\Python34\lib\subprocess.py", line 858, in __init__
        restore_signals, start_new_session)
      File "C:\Python34\lib\subprocess.py", line 1111, in _execute_child
        startupinfo)
    TypeError: environment can only contain strings

We shouldn't be calling `utils.bytes_environ` on Python 3 under Windows. Moreover, I think we are doing it at a wrong place. Instead of converting what we get from the environment, we should be sanitizing what we pass to `subprocess.Popen`. Then we won't need separate logic for setting `LANGUAGE` on Windows.

I think it's bad enough to require a fix before 2.18.1. We promise Python 3 support in 2.18, it's a Python 3 issue.

I'll be mostly offline until Tuesday. I want to make sure we won't release 2.18.1 with that bug.

**Comment by wbsoft** [comment]
I can't test python3 under windows...

**Comment by wbsoft** [comment]
@proski, are you able to fix this issue in the described way? I don't have a windows machine with python 3, popplerqt4, portmidi etc compiled for python 3 etc available.

**Comment by proski** [comment]
Too many things have changes since then. I don't have that development machine anymore, and I'm quite short on time. I still remember that code. It's the case when refactoring is badly needed, but the result would need to be tested on many OSes and versions of Python. I'll keep this issue in mind, but I'm not sure if I would be able to deal with it soon.

**Comment by wbsoft** [comment]
thank you for replying :) I think I'll advertise that using python 3 on Windows needs testing, and have the released prebuilt standalone Windows installer still use Python 2. I test those briefly for every release.

**Comment by uliska** [comment]
Is that still relevant?
