### ISSUE TITLE
[Frescobaldi 2.17.2] ValueError: invalid literal for int() with base 10: '' 

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#669]
Reported by a user:

```
Frescobaldi: 2.17.2

Python: 2.7.9 -- Qt: 4.8.6 -- PyQt4: 4.11.3 -- sip: 4.16.5
OS: Darwin-14.0.0-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/scorewiz/dialog.py", line 110, in slotAccepted
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/scorewiz/build.py", line 225, in __init__
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/scorewiz/build.py", line 277, in makeBlock
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/scorewiz/build.py", line 360, in makeParts
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/scorewiz/parts/vocal.py", line 647, in build
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/scorewiz/scoreproperties.py", line 269, in schemeMidiTempo
ValueError: invalid literal for int() with base 10: ''
```

**Comment by wbsoft** [comment]
Happens in scorewiz with MIDI output on and Show Metronome Value off.
