### ISSUE TITLE
[Frescobaldi 2.18.1] UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#674]
reported by a user:
```
Frescobaldi: 2.18.1

Python: 2.7.6 -- Qt: 4.8.6 -- PyQt4: 4.10.4 -- sip: 4.15.5
python-ly: 0.9.1
poppler: unknown -- python-poppler-qt4: unknown
OS: Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/frescobaldi_app/documentactions.py", line 131, in convertLy
    convert_ly.convert(self.mainwindow())
  File "/usr/local/lib/python2.7/dist-packages/frescobaldi_app/convert_ly.py", line 56, in convert
    dlg.run()
  File "/usr/local/lib/python2.7/dist-packages/frescobaldi_app/convert_ly.py", line 256, in run
    self.setDiffText(out)
  File "/usr/local/lib/python2.7/dist-packages/frescobaldi_app/convert_ly.py", line 183, in setDiffText
    _("Current Document"), _("Converted Document")))
  File "/usr/lib/python2.7/difflib.py", line 1203, in unified_diff
    yield '--- {}{}{}'.format(fromfile, fromdate, lineterm)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)


I was trying to convert-ly.
```

**Comment by PeterBjuhr** [comment]
Some research tells me this happens when a language has non-ascii characters for the translation of "Current Document" or "Converted Document". The `UnicodeEncodeError` occurs with several languages, although I haven't found which language gives this exact message.

Why these strings are encoded with to ascii I don't know...

**Comment by wbsoft** [comment]
I think we should not use the translated "Current Document" and "Converted Document" inside the diff, although the fault is in difflib, which does not use unicode strings in the format string.
