### ISSUE TITLE
Regression in Quickinsert

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#701]
````
Traceback (most recent call last):
  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/quickinsert/buttongroup.py", line 96, in <lambda>
    function = (lambda name: lambda: self.actionTriggered(name))(name)
  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/quickinsert/spanners.py", line 191, in actionTriggered
    for s, c in zip(spanner, spanner_positions(cursor)):
  File "/home/peter/frescob-dev/frescobaldi/frescobaldi_app/quickinsert/spanners.py", line 281, in spanner_positions
    for p in ly.rhythm.music_tokens(source)]
AttributeError: 'module' object has no attribute 'music_tokens'
````

`Quickinsert` needs to be adjusted to the latest changes in `ly.rhythm`.

**Comment by wbsoft** [comment]
Oops!

**Comment by PeterBjuhr** [comment]
`music_tokens` is also used in `dynamics.py` and `articulations.py`.
