### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/var/folders/3_/fhptxgks4vd0t5spsm5mbjd80000gn/T/frescobaldi-bG2p9V/tmpwlpyOb'

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#776]
reported by a mac user:

```
Frescobaldi: 2.18.1 -- Python: 2.7.10 -- python-ly: 0.9.2 -- Qt: 4.8.7 -- PyQt: 4.11.4 -- sip: 4.16.9 -- poppler: 0.32.0 -- python-poppler-qt: 0.24.0 -- OS: Darwin-14.5.0-x86_64-i386-64bit

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/__init__.py", line 140, in engraveRunner
    self.engravePreview()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/__init__.py", line 144, in engravePreview
    self.engrave('preview')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/__init__.py", line 195, in engrave
    self.runJob(command.defaultJob(doc, args), doc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/engrave/command.py", line 53, in defaultJob
    filename, includepath = documentinfo.info(document).jobinfo(True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/documentinfo.py", line 201, in jobinfo
    scratch.saveDocument()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/scratchdir.py", line 84, in saveDocument
    self.create()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/scratchdir.py", line 65, in create
    self._directory = util.tempdir()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/util.py", line 109, in tempdir
    return tempfile.mkdtemp(dir=_tempdir)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 333, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/var/folders/3_/fhptxgks4vd0t5spsm5mbjd80000gn/T/frescobaldi-bG2p9V/tmpwlpyOb'

Optionally describe below what you were doing:

I click on the “New” icon and get a blank entry panel with a version statement.  I then click on the
“Engrave (preview)” icon.  At that point I get the “Internal Error - Frescobaldi” popup window with the
above traceback.  The same thing happens if I enter, say, “{ c’ }” into the entry panel before clicking
on “Engrave (preview)”.

In a terminal window I “cd /var/folders/3_/fhptxgks4vd0t5spsm5mbjd80000gn/T” and then “ls -al” and the result is:

total 0
drwx------  13 pat  access_bpf  442 Oct 25 11:24 .
drwxr-xr-x   7 pat  access_bpf  238 Oct 21 16:20 ..
drwx------   3 pat  access_bpf  102 Oct 25 04:10 .AddressBookLocks
drwx------   2 pat  access_bpf   68 Oct 21 16:20 .CalendarLocks
drwx------   2 pat  access_bpf   68 Oct 24 10:14 MediaCache
drwxr-xr-x   2 pat  access_bpf   68 Oct 25 05:06 TemporaryItems
drwx------@  2 pat  access_bpf   68 Oct 21 17:10 com.apple.AddressBook.InternetAccountsBridge
drwx------@  2 pat  access_bpf   68 Oct 21 16:44 com.apple.MediaLibraryService
drwx------@  3 pat  access_bpf  102 Oct 24 08:52 com.apple.mail
drwx------   2 pat  access_bpf   68 Oct 23 13:28 com.apple.qtkitserver
drwx------   2 pat  access_bpf   68 Oct 23 13:28 com.apple.qtkittrustedmoviesservice
drwx------@  2 pat  access_bpf   68 Oct 21 16:20 com.apple.quicklook.ui.helper
drwx------@  2 pat  access_bpf   68 Oct 21 16:23 com.getdropbox.dropbox.garcon

and sure enough there is no file there with the name "frescobaldi-bG2p9V”.  At that point I do “mkdir
frescobaldi-bG2p9V” and click on the “Engrave (Preview)” icon and the compilation is successfully
completed.  At that point if i do:  “cd frescobaldi-bG2p9V;pwd;ls -al”, I get”

Pats-Mac-Pro:frescobaldi-bG2p9V pat$ pwd
/var/folders/3_/fhptxgks4vd0t5spsm5mbjd80000gn/T/frescobaldi-bG2p9V
Pats-Mac-Pro:frescobaldi-bG2p9V pat$ ls -al
total 0
drwxr-xr-x   3 pat  access_bpf  102 Oct 25 11:32 .
drwx------  14 pat  access_bpf  476 Oct 25 11:31 ..
drwx------   3 pat  access_bpf  102 Oct 25 11:32 tmpxuY4Lh

In that directory there is a file, document.ly <http://document.ly/>:

Pats-Mac-Pro:tmpxuY4Lh pat$ ls -al
total 8
drwx------  3 pat  access_bpf  102 Oct 25 11:32 .
drwxr-xr-x  3 pat  access_bpf  102 Oct 25 11:32 ..
-rw-r--r--  1 pat  access_bpf   20 Oct 25 11:32 document.ly

and the content of document.ly <http://document.ly/> is:

Pats-Mac-Pro:tmpxuY4Lh pat$ cat document.ly
\version “2.19.28"

I guess the crucial question is why can’t Frescobaldi create the directory frescobaldi-bG2p9V in
/var/folders/3_/fhptxgks4vd0t5spsm5mbjd80000gn/T?

All this is on a Mac Pro with 16GB ram and running OSX 10.10.5 and LilyPond 2.19.28.

```

It seems the temporary master directory is not properly created. 

The function `tempdir()` in `util.py` is responsible for this. Can a mac user debug this?

**Comment by dliessi** [comment]
See #554.
So far I've been unable to replicate the issue on any OS X version (until 10.10, I haven't had access to the new 10.11 yet).

**Comment by dliessi** [comment]
If I understand correctly, `tempdir()` is just a wrapper around `tempfile.mkdtemp`, so I believe (but I could be plain wrong) that this is not a bug in Frescobaldi.

**Comment by dliessi** [comment]
> So far I've been unable to replicate the issue on any OS X version [...]

Both this issue and #554 are on Mac 10.10, though, so maybe it is something specific to that system.
I'll do more tests as soon as I'll be around the 10.10 machine again, but I've been unable to replicate the issue in the past, so don't hold your breath.

**Comment by dliessi** [comment]
Issue https://github.com/MDAnalysis/mdanalysis/issues/556 referencing this one has interesting info on this apparently random problem, and they also have a fix (`tempdir.in_tempdir()`, see https://github.com/MDAnalysis/mdanalysis/pull/558 and https://github.com/MDAnalysis/mdanalysis/commit/f1345fafd26dbc84b316774b753ecce468179c4a).
@wbsoft Could you please have a look at it?

**Comment by luoluoxiaozhu** [comment]
我也遇到这样的问题，把Cydia中openSSH 和OpenSSH Clients卸载，重新安装OpenSSH即可（
