### ISSUE TITLE
Can't Engrave

### ISSUE THREAD

**Issue by wmwilson** [wbsoft/frescobaldi#814]
Help! I've used Frescobaldi for years and love it. All of a sudden it stopped working. I tried to update but still get the following error. I'm just a lowly musician and can't make heads or tales of what is wrong. Please help! Thanks,
William

Frescobaldi: 2.18.2 -- Python: 2.7.6 -- python-ly: 0.9.3 -- Qt: 4.8.6 -- PyQt: 4.10.4 -- sip: 4.15.5 -- poppler: unknown -- python-poppler-qt: unknown -- OS: Linux-4.2.0-35-generic-x86_64-with-Ubuntu-14.04-trusty

Traceback (most recent call last):
File "/home/william/Downloads/frescobaldi-2.18.2/frescobaldi_app/engrave/__init__.py", line 140, in engraveRunner
self.engravePreview()
File "/home/william/Downloads/frescobaldi-2.18.2/frescobaldi_app/engrave/__init__.py", line 144, in engravePreview
self.engrave('preview')
File "/home/william/Downloads/frescobaldi-2.18.2/frescobaldi_app/engrave/__init__.py", line 195, in engrave
self.runJob(command.defaultJob(doc, args), doc)
File "/home/william/Downloads/frescobaldi-2.18.2/frescobaldi_app/engrave/command.py", line 55, in defaultJob
i = info(document)
File "/home/william/Downloads/frescobaldi-2.18.2/frescobaldi_app/engrave/command.py", line 40, in info
return lilypondinfo.preferred()
File "/home/william/Downloads/frescobaldi-2.18.2/frescobaldi_app/lilypondinfo.py", line 97, in preferred
infos_ = infos()
File "/home/william/Downloads/frescobaldi-2.18.2/frescobaldi_app/lilypondinfo.py", line 56, in infos
info = LilyPondInfo.read(s)
File "/home/william/Downloads/frescobaldi-2.18.2/frescobaldi_app/lilypondinfo.py", line 364, in read
info.versionString = settings.value("version", "", type(""))
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 10

Optionally describe below what you were doing:

Happens Every time I hit Engrave. Then when I try again it says it can't find lilypond.

**Comment by wmwilson** [comment]
Solved it. Hit reset in preferences. Possibly corrupt preferences file? Anyway it's working again. Phew.

**Comment by wbsoft** [comment]
Hi, thanks for reporting. Although I'm glad you could get back to working, I reopen this issue because such a faillure should not happen :-)

**Comment by ismailsunni** [comment]
Googling my problem, took me here. Same problem. I don't have better solution that catch the TypeError. Comment here, just in case you solved the problem. Or I can update mine if I solve the problem. Thanks
