### ISSUE TITLE
clicking "Email Bug Report..." button generates exception (python 3)

### ISSUE THREAD

**Issue by shimpe** [wbsoft/frescobaldi#821]
Traceback (most recent call last):
  File "/home/development/python/frescobaldi/frescobaldi/frescobaldi_app/exception.py", line 75, in done
    self.reportBug()
  File "/home/development/python/frescobaldi/frescobaldi/frescobaldi_app/exception.py", line 79, in reportBug
    bugreport.email(self._tbshort, self._tbfull + '\n' + _("Optionally describe below what you were doing:"))
  File "/home/development/python/frescobaldi/frescobaldi/frescobaldi_app/bugreport.py", line 37, in email
    url.addQueryItem("subject", subject)
AttributeError: 'QUrl' object has no attribute 'addQueryItem'

latest github commit 79b2e0a0ac6df19c59b7626e043d98a0ec896703

**Comment by wbsoft** [comment]
Thank you!
