### ISSUE TITLE
pressing ctrl+f  generates exception

### ISSUE THREAD

**Issue by shimpe** [wbsoft/frescobaldi#822]
Traceback (most recent call last):
  File "/home/development/python/frescobaldi/frescobaldi/frescobaldi_app/mainwindow.py", line 851, in find
    import search
  File "/home/development/python/frescobaldi/frescobaldi/frescobaldi_app/search/__init__.py", line 44, in <module>
    import widgets.borderlayout
ImportError: bad magic number in 'widgets.borderlayout': b'\x03\xf3\r\n'

(using python3 on latest github commit 79b2e0a0ac6df19c59b7626e043d98a0ec896703)

**Comment by shimpe** [comment]
search/__init__.py still refers to widgets.borderlayout, but borderlayout appears to have been moved to gadgets/.

**Comment by wbsoft** [comment]
Fixed, thanks!
