### ISSUE TITLE
Different V3 issues on Debian 8.4

### ISSUE THREAD

**Issue by andrewbernard** [wbsoft/frescobaldi#826]
The current head from the master branch run with python3 on a clean install of a Debian 8.4 machine displays core dumping behaviour which is hard to debug. Without going into details, in order to solve this, I have installed a pristine Debian 8.4 VM and make a painstakingly careful build and install of the prequisites, such as I understand them to be, which is not entrrely clear from the limited information in the INSTALL file (do you use the Debian packages, or external ones?)

Now, I see the following when running

`python3 frescobaldi`

in the top level directory.

```
Traceback (most recent call last):
  File "frescobaldi", line 7, in <module>
    import main
  File "/home/andro/src/frescobaldi/frescobaldi_app/main.py", line 33, in <module>
    from PyQt5.QtCore import QSettings, QTimer, QUrl
RuntimeError: the sip module implements API v11.0 to v11.1 but the PyQt5.QtCore module requires API v11.3
```
What is going on here? There is some sort of sip version mismatch which I am unable to solve.

At the shell prompt we have:
```
$ sip -V
4.18
```

From python3 we have:
```
$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sip
>>> print(sip)
<module 'sip' from '/usr/lib/python3/dist-packages/sip.cpython-34m-x86_64-linux-gnu.so'>
>>> print(sip.SIP_VERSION_STR)
4.16.4
```

All assistance appreciated. Neither Urs nor I can get F3 going on Debian 8, as we both seem to have different issues.

Andrew

**Comment by uliska** [comment]
OK, my issues are different (as outlined in #818), the common ground is that we both are running Debian 8.4. (But as I have Linux Mint Debian edition we *still* seem to have some packages in different versions).

```
$ sip -V
4.16.4
```

But I have the impression that this isn't even necessary. I *had*

```
$ sip -V
The program 'sip' is currently not installed.  To run 'sip' please ask your administrator to install the package 'sip-dev'
```
without any differences.

```
$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sip
>>> print (sip)
<module 'sip' from '/usr/lib/python3/dist-packages/sip.cpython-34m-x86_64-linux-gnu.so'>
>>> print(sip.SIP_VERSION_STR)
4.16.4
```

So it seems the `sip` *program* that you have from the `sip-dev` package is at another version than the `sip` *module* that is installed in Python, presumably from the `python3-sip` package, which is at 4.16.4 in my system.

**Comment by fedelibre** [comment]
It looks like a stale issue. Should be closed?
