### ISSUE TITLE
Internal Error when exporting musicXml

### ISSUE THREAD

**Issue by vt45** [wbsoft/frescobaldi#883]
Ubuntu 16.10
Frescobaldi 2.18.1

Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/file_export/__init__.py", line 64, in exportMusicXML
    writer.parse_text(doc.toPlainText())
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 102, in parse_text
    self.parse_document(doc)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 119, in parse_document
    self.parse_tree(mustree)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 133, in parse_tree
    self.parse_nodes(mus_nodes)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 145, in parse_nodes
    func_call(m)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 624, in End
    self.mediator.check_simultan()
  File "/usr/lib/python3/dist-packages/ly/musicxml/ly2xml_mediator.py", line 293, in check_simultan
    self.sections.pop()
IndexError: pop from empty list

**Comment by uliska** [comment]
This is an issue in the underlying `python-ly` library, and it has actually been reported as https://github.com/wbsoft/python-ly/issues/76. So I close *this* one.
