### ISSUE TITLE
Snippets Menu

### ISSUE THREAD

**Issue by bmgxc9** [wbsoft/frescobaldi#894]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/snippet/menu.py", line 64, in populate
    from . import model, snippets, actions
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/snippet/model.py", line 34, in <module>
    from . import snippets
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/snippet/snippets.py", line 34, in <module>
    import symbols
  File "/usr/lib/python3.6/site-packages/frescobaldi_app/symbols/__init__.py", line 31, in <module>
    from PyQt5.QtSvg import QSvgRenderer
ImportError: libQt5Svg.so.5: cannot open shared object file: No such file or directory

**Comment by bmgxc9** [comment]
The problem seems resolved in the most recent builds.

**Comment by wbsoft** [comment]
QtSvg needs to be installed.
