### ISSUE TITLE
Frescobaldi 3.0.0 does not import MusicXML

### ISSUE THREAD

**Issue by tobik** [wbsoft/frescobaldi#910]
Reproduce steps:
1. Menu File > Import MusicXML
2. Select a MusicXML file
3. Execute musicxml2ly 

Expect: The import dialog disappears and a new code window with the generated ly file should open
Actual: The import dialog disappears but nothing else

**Comment by Schroedingers-Cat** [comment]
I have the same problem using Import MIDI. Seems like the entire import of Frescobaldi 3 is broken.

Can any of the devs try to reproduce this?

I'm using Frescobaldi on Windows 10x64 with LilyPond 2.19.58-1. Frescobaldi is using the correct LilyPond path.

**Comment by uliska** [comment]
Could either of you share a MusicXML or MIDI file you used?

I coincidentally tried to import a MusicXML file a few days ago, and I
*did* get the corresponding LilyPond file opened in the editor.

**Comment by Schroedingers-Cat** [comment]
I didn't find a MIDI that worked, so I just grabbed one of them:
[mi-midi.zip](https://github.com/wbsoft/frescobaldi/files/888033/mi-midi.zip)

**Comment by tobik** [comment]
Not a single MusicXML file is getting imported. This is probably not a issue of a specific import file.

I am also running Windows 10x64. Maybe it is a Windows issue?

**Comment by Schroedingers-Cat** [comment]
@uliska were you able to reproduce this bug?

**Comment by benignoc** [comment]
I am getting the same problem.

**Comment by soundsfromsound** [comment]
I can confirm also that Frescobaldi 3 on Windows 10 does not import any MIDI or MusicXML file. 

Invoking musicxml2ly / LilyPond from the command line works just fine, it's just from within Frescobaldi that this import MIDI / MusicXML won't work correctly for any file I've tried so far.

**Comment by benignoc** [comment]
This happened to me, and it was solved by reinstalling frescobaldi, have
you tried that ?.

**Comment by soundsfromsound** [comment]
I tried re-installing Frescobaldi but it will not import MusicXML or MIDI on **Windows 10.** 
However, I am able to do this on Linux Mint now. 

Linux Mint does indeed import both file types correctly after a fresh re-install however. So that is good!

**Comment by tjin92** [comment]
I was running Frescobaldi 3.0.1 on Windows 7 and MusicXML import was failing. Uninstalling and reinstalling did not fix the problem.

After going back to 2.20.0 it now works again.

**Comment by fedelibre** [comment]
I'll make a try once I have access to a Windows machine (in September)

**Comment by JayCeeH** [comment]
I've got the same problem: Windows 10 Pro 64, Frescobaldi 3.0.1, and MusicXML / MIDI import doesn't work.

**Comment by fedelibre** [comment]
I confirm it. I've just tested it on Windows 7 and Frescobaldi 3.0.1.

It sounds like the issue [recently discussed](https://lists.gnu.org/archive/html/lilypond-user/2018-09/msg00139.html).

**Comment by fedelibre** [comment]
When I run Frescobaldi from source on Windows, the import works. The print shows that python bundled in LilyPond is used:

```
fede@federico MINGW64 ~/git/frescobaldi (import-910)
$ ./frescobaldi.exe
['C:/Program Files (x86)/LilyPond/usr/bin\\python-windows.exe', 'C:/Program Files (x86)/LilyPond/usr/bin\\midi2ly.py', 'Z:/intro1.mid', '--output=C:\\Users\\fede\\AppData\\Local\\Temp\\frescobaldi-yjrf1_fl\\tmpk1ka4fkk\\intro1.ly']
```

Perhaps the installation behaves differently? How can I debug it?

**Comment by uliska** [comment]
When you have an installation from the installer you should nevertheless 
be able to edit the Python files. So you should be able to produce the 
same debug print() statement.

**Comment by fedelibre** [comment]
I know, but the source is changed, as you know well :-)
Can you check the 3.0.0 tag and tell me which file should I edit? I don't have time now, I'll test it tomorrow.

**Comment by uliska** [comment]
Ah, yes of course, silly me ...

it should be in `file_import/toly_dialog.py` after line 151
https://github.com/wbsoft/frescobaldi/blob/v3.0.0/frescobaldi_app/file_import/toly_dialog.py#L151

There you should insert
```python
print(cmd) 
```

**Comment by fedelibre** [comment]
I edited the file and launched Frescobaldi installation from Git Bash.
It seems that the problem is the `--output` option here:

```
fede@federico MINGW64 ~
$ /C/Program\ Files\ \(x86\)/Frescobaldi/frescobaldi.exe
['C:/Program Files (x86)/LilyPond/usr/bin\\python-windows.exe', 'C:/Program Files (x86)/LilyPond/usr/bin\\midi2ly.py', 'Z:/intro1.mid', '--output', '-']
Traceback (most recent call last):
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\__init__.py", line 120, in importMidi
    self.openMidiDialog()
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\__init__.py", line 130, in openMidiDialog
    self.runImport()
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\__init__.py", line 159, in runImport
    stdout, stderr = dlg.run_command()
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_import\toly_dialog.py", line 173, in run_command
    stderr = subprocess.PIPE)
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
TypeError: environment can only contain strings
```

**Comment by uliska** [comment]
That is not necessarily true because the old code had a completely different approach: It read the external scripts' standard output into an empty document. The new code performs the conversion into a file and then uses that resulting file.

So since you could successfully import files through the code from the Git repository I *assume* that I have "accidentally" fixed this issue.

I leave it open, and we should check it after the next Windows release.
