### ISSUE TITLE
3.0.0 build/dmg for Mac OS X

### ISSUE THREAD

**Issue by msikma** [wbsoft/frescobaldi#986]
As far as I can see, there is currently no 3.0.0 dmg for Mac OS X. The latest is 2.20.0. Are there any plans for a dmg for OSX, or is there possibly a problem preventing it from being built?

**Comment by dliessi** [comment]
There is a plan for a Frescobaldi 3 build for macOS, but I've been unable to solve all the issues I'm having in making version 3 work on macOS.

I'm on a trip this week. When I'm back I'll try to fix the remaining problems or open corresponding issues here on GitHub.

**Comment by msikma** [comment]
Thanks for the quick response! I'm really glad you're planning to work on this. Wish I could be of some help. I can build for OSX but I doubt I'd be much use in tracking down whatever last bugs there are...

**Comment by wkechel** [comment]
Are there any news on this issue. I am trying to install frescobaldi via homebrew on high sierra but get the error message:
Error: No available formula with the name "frescobaldi"
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

frescobaldi was deleted from homebrew/core in commit 4113ec559:
  frescobaldi: migrate to boneyard (https://github.com/Homebrew/homebrew-core/issues/5715)

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 4113ec559^:Formula/frescobaldi.rb

If you still use this formula consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html

Since I do not know how to do this situation I am looking for a dmg-file for 3.x

**Comment by marnen** [comment]
@wkechel Don't use the Homebrew formula for Frescobaldi; I've stopped maintaining it since a native Mac app is now available. Frescobaldi 2.20 is available as a [cask](https://caskroom.github.io/). I will update the cask for 3.0 when a Mac build is available.

**Comment by sysadm-prs-de** [comment]
Thanks for the hint. I am currently using the 2.x standalone version. Just got the idea to update when I detected the new version. I appreciate any news concerning osx.

**Comment by marnen** [comment]
I should also say that if it looks like an Aqua build of 3.0.0 will be delayed much longer, I'm willing to resuscitate and update the Homebrew formula. But I hope I won't have to.

**Comment by msikma** [comment]
Having some documentation on what the problems are for making a build would be nice. Maybe they are just things that come up naturally during compiling? (Haven't tried it myself yet.) But if they are non-obvious it might be worth having separate issues for others to look at and maybe send in a PR for.

**Comment by marnen** [comment]
What are the current problems with the Mac build? This issue has been open for months. How can I help?

**Comment by sysadm-prs-de** [comment]
I can provide help for the mac port as well, but currently I have no clue how th ebuild process looks like and what is missing. Can anybody give directions?

**Comment by dliessi** [comment]
I'm sorry for not even answering for so long.
I'm working again on this issue and I'll report on it later.

**Comment by dliessi** [comment]
Ok, I had a look at the current situation.
I'm able to run Frescobaldi and most things seem to work.

The most notable thing that is currently not working is the insertion of snippets and templates from the menus, while using the keyboard shortcuts or the snippet manager seems to work correctly.
There are also some minor graphical glitches, such as the file name being cut in the tab label.
I remember that some months ago there were problems in displaying the icons in menus, but they seem to have disappeared with some update in either Qt5 or PyQt5.

Overall the application is quite usable.
If there is an interest, I may provide a prebuilt application bundle for you to test, while I work on the mentioned issues.

**Comment by wkechel** [comment]
Yes, I am interested and I can test. Please let me know when you are ready.

**Comment by marnen** [comment]
I can also test a Mac build (or attempt to produce one...).

**Comment by marnen** [comment]
@dliessi How are you dealing with installing python-poppler-qt5? When I try, I run into https://github.com/wbsoft/python-poppler-qt5/issues/14.

**Comment by marnen** [comment]
@dliessi:

> The most notable thing that is currently not working is the insertion of snippets and templates from the menus, while using the keyboard shortcuts or the snippet manager seems to work correctly.
There are also some minor graphical glitches, such as the file name being cut in the tab label.

Confirmed all of these on Mac OS 10.12 (Sierra) with Python 3.6.3. Oy.

**Comment by dliessi** [comment]
I build python-poppler-qt5 with MacPorts.
I had to backport wbsoft/python-poppler-qt5@faf4d1308f89560b0d849671226e3080dfc72e79 and wbsoft/python-poppler-qt5#19.
See https://github.com/macports/macports-ports/tree/master/python/py-poppler-qt5 for the current status and macports/macports-ports#1063 for the latest pending update.

**Comment by marnen** [comment]
@dliessi All right, then we need to figure out a build process that doesn't require the disaster that is MacPorts. I suppose I could make a Homebrew package for python-poppler-qt5.

**Comment by marnen** [comment]
Actually, some of the suggestions on https://github.com/wbsoft/python-poppler-qt5/issues/14 are worth a try first. But even before that, I'd like to get the other issues dealt with...

**Comment by mojca** [comment]
@dliessi: the MacPorts dependencies are now up to date, so you can submit frescobaldi update once you have it available.

**Comment by dliessi** [comment]
I've been trying to build an application bundle for Frescobaldi 3, but I cannot make py2app work with it as it works with Frescobaldi 2.
Before spending more time on this, I'm going to work on a Portfile for Frescobaldi 3, so that it can be installed via MacPorts.
Only then I'll resume the work on the standalone application bundle.

**Comment by marnen** [comment]
@dliessi Thank you again for all your work on this. I submit that developing a Portfile is somewhat a waste of time, since very few people are still using MacPorts AFAIK. But of course we can always translate it to a Homebrew formula...

However, I suppose that's a nitpick. The larger issue: what is py2app doing or not doing at the moment? Just saying that you "can't make it work" isn't all that useful; if you describe what's going on in more detail, perhaps others can help.

**Comment by dliessi** [comment]
There weren't many details I could provide: py2app produced an application apparently without errors, but which crashed on startup.
However, while trying to be more specific and investigate the issue in more detail, I noticed I had left out a step in producing the application bundle (i.e., manually copying the Qt5 SVG library file inside the application bundle _before_ running macdeployqt on it), and that was indeed a key step since I now seem to be closer to a working application bundle.
OK, I reversed my priority list again and I'll spend more time on the application bundle today. :)

**Comment by dliessi** [comment]
You can find [here](https://www.dropbox.com/s/xdcqzkdlkwxlxjd/Frescobaldi-3.0.0-20171221-x86_64.dmg?dl=0) (SHA256: 687171532864485a6e220ed7d0a0488c4443539304c553e45767d11e69535772) a DMG containing a build of Frescobaldi.app from current master (with a couple of changes I will push soon).
If you are interested, please try it and report any problems you encounter (recall the ones already mentioned in https://github.com/wbsoft/frescobaldi/issues/986#issuecomment-347517835).

**Comment by marnen** [comment]
@mojca:
> Can we please stop judgements about usefulness of (time spent doing X for) software? In particular if you are not able to show any numbers supporting your claims.

I probably shouldn't even respond to this, but...we only have limited time and resources available to us, apparently; that's the nature of most software projects, especially volunteer-driven OSS. As such, it makes sense to think about the best way to allocate those resources. I don't understand the idea that we shouldn't be making judgements; IMHO that's exactly what our critical thinking faculties are for. 

If I had numbers, I'd provide them; I don't think such things are available for OSS. But the fact remains that except for @dliessi and you, I haven't heard of *anyone* using MacPorts in many years, because it's so clumsy and hard to work with; the entire community (that I have contact with) has switched to Homebrew. It makes little sense to have Homebrew and MacPorts on the same computer, so a MacPorts-based approach is not terribly useful for what is probably the larger part of the user community. (Of course, a MacPorts port *could* be translated to a Homebrew formula, so it isn't entirely useless.)

**Comment by marnen** [comment]
@dliessi Awesome! I'll check out the new build.

**Comment by marnen** [comment]
@dliessi I'm trying out the new build. As you know, it still has the same problems as mentioned earlier, so it's not really usable yet. Was it supposed to fix any problems, or just get a build process working for a standalone .app? If it was just supposed to do the latter, then I can report success.

**Comment by francisperea** [comment]
@dliessi I've downloaded you DMG and successfully compiled 2 little pieces, both to PDF and MIDI under OS X 10.13.2. Thanks a lot for your work.

**Comment by dliessi** [comment]
@marnen It was just the latter: now that I have a reliable way to produce an .app bundle capable of running, we can focus on finding and fixing bugs.

@francisperea Please test it with your usual workflow and report any problems. The more functions you test, the more likely bugs are to come to surface.

**Comment by marnen** [comment]
@dliessi Great. I continue to be happy to help, but I don't know where to start looking with the (presumed) qt5 issues.

**Comment by marnen** [comment]
@dliessi:

> a DMG containing a build of Frescobaldi.app from current master (with a couple of changes I will push soon).

Did you push them yet? If so, where can I find them?

**Comment by dliessi** [comment]
They're in current master. They were mostly about the build process and didn't tackle the Qt 5 problems.

**Comment by dliessi** [comment]
Of the Qt 5 issues, the most serious one is the broken insertion of snippets and templates from the menus.
I tried to look into the corresponding code (https://github.com/wbsoft/frescobaldi/blob/master/frescobaldi_app/snippet/menu.py) but haven't found the problem so far.

**Comment by juanalexei** [comment]
I noticed that this version does not cope well with international characters in the log window and in file names. May be some encoding to set somewhere. I haven't tried yet to build Frescobaldi myself to see if it reproduces and if I have to do a separate report for this.

**Comment by marnen** [comment]
Any progress? Can I help somehow?

**Comment by dliessi** [comment]
To everyone interested in Frescobaldi 3 on Mac:

Issues #1073 and #1086 have been solved.
You can find [here](https://www.dropbox.com/s/bj5wgn9t89gm4mx/Frescobaldi-3.0.0-20180806-x86_64.dmg?dl=0) (SHA256: `517e9e2e7ae2fc892881a3d69814f7930cfb5351ac1932b3a0512c45712a9e08`) a DMG containing a build of Frescobaldi.app from current master.
I would appreciate if you could test it and report any problems.
Issue #1087 is still unsolved.

**Comment by dliessi** [comment]
@juanalexei Regarding your comment https://github.com/wbsoft/frescobaldi/issues/986#issuecomment-375684629: I noticed some problems in document tabs with non-ASCII characters in file names (I'll open an issue later), but not in the log window.
Can you describe the problem in more detail (and maybe post a screenshot)?

**Comment by simonkeys** [comment]
Just installed the new build. Retina support looks great, but I can't resize the music view window. Is that just me?

**Comment by nagymusic** [comment]
Just sending quick feedback. I've been using Frescobaldi 3.0.0 on Mojave, installed as explained above (see the comment by dliessi in regards to the Mac's DMG). Frescobaldi is working fine, except that when I quit the application, I receive the following error message:

`Frescobaldi quit unexpectedly.`

`Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple.`

I attached the error log in case someone wants to have a look and offer suggestions. Thank you!
[Frescobaldi-error_message.pdf](https://github.com/frescobaldi/frescobaldi/files/3174428/Frescobaldi-error_message.pdf)

**Comment by fedelibre** [comment]
How did you close the application? The crash happens whatever method you use to close the application (clicking on the X icon, clicking File>Quit menu or Ctrl-Q)? Or just with  specific method?

Just wondering if it might be related to issue #1120

**Comment by marnen** [comment]
@fedelibre Quick note: none of those work quite as stated on Mac OS. You meant clicking the close box (which actually *shouldn’t* quit a Mac application!), selecting Quit from the Frescobaldi menu, or pressing Cmd-Q respectively. :)

None of this is a terribly big deal, but in a Mac-specific thread, you may want to keep in mind how Mac OS UI typically works.

**Comment by marnen** [comment]
Playing around with the DMG on Mojave as well.

When the app opens, I get the following error:
```
Traceback (most recent call last):
  File "/private/var/folders/yq/n3t_19_13897mtqk4w1lx7jc0000gq/T/AppTranslocation/EF3958AC-8D5F-4D76-9E97-CDEA5D3B62D9/d/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/sessions/menu.py", line 100, in populate
ValueError: too many values to unpack (expected 2)
```
Clicking "cancel" either has no effect or brings up the error alert again; ditto the close box. Clicking "email bug report" opens Mail.app and then returns to the error. The error alert is modal; all non-system menu items are disabled, and clicking on the application window just gets an error beep. Even the Quit menu item is disabled, and so I have to force-quit Fresco.

**Comment by marnen** [comment]
Hmm, when I copied to a location other than the DMG, I still got the error but was *eventually* able to cancel my way out of it. But then it reappeared every time I switched focus back to the application. This build is thus essentially unusable on my Mac, but I appreciate @dliessi helping us get *a little* closer.

**Comment by nagymusic** [comment]
> How did you close the application? The crash happens whatever method you use to close the application (clicking on the X icon, clicking File>Quit menu or Ctrl-Q)? Or just with specific method?
> 
> Just wondering if it might be related to issue #1120

Just a quick update that the crash happens only when clicking on the X icon. Ctrl-Q or File>Quit menu works fine. Reading the above thread, I understand that not everyone is having the same experience. I'm just glad that Frescobaldi can be closed without an error message report... Thank again for your feedback! 

By the way, would you happen to know if 3.0.1 may be available for Mac or Linux? I've been using this newer version on Windows and I like some of the new functionality.

**Comment by fedelibre** [comment]
> By the way, would you happen to know if 3.0.1 may be available for Mac or Linux any time soon? I've been using this newer version on Windows and I like some of the new functionality.

I think a new *minor* release (3.0.1) is blocked only because of problems with building installers for Windows and Mac. On the other hand, [3.1 release](https://github.com/frescobaldi/frescobaldi/projects/5) has still a lot of TODO items.

Anyway, do you know you can easily run Fresco from source in Linux? There's a tutorial in the wiki.

**Comment by uliska** [comment]
I *think* that there is a "newer" Windows release, but that was *only* a Windows-related bug fix. There is nothing in any *released* Windows version that would qualify as "new functionality".

Basically the idea of a 3.0.1 release was discarded in favor of a more comprehensive 3.1 release (I thought such a small step would be somewhat embarrassing after more than two years). Unfortunately it seems 3.1 is still further away than desirable - we would really need a few people contributing actively to Frescobaldi ...

**Comment by marnen** [comment]
@fedelibre:

> I think a new minor release (3.0.1) is blocked only because of problems with building installers for Windows and Mac. 

That sounds implausible to me. I thought that version 3 hadn’t been released for Mac yet because of the outstanding bugs, and it is certainly possible to run it from source on Mac OS, so why would an installer be any more difficult than it was for version 2?

**Comment by fedelibre** [comment]
@marnen See above comment from Urs.

Also, there were [problems with python-poppler-qt5 on Mac](https://github.com/frescobaldi/python-poppler-qt5/issues/28).

**Comment by dliessi** [comment]
Dear all,
the application bundle for Frescobaldi 3.1 is now [available](https://github.com/frescobaldi/frescobaldi/releases/tag/v3.1).

I would appreciate if you could try it out and check whether the issues you had with the previous builds are still there and whether there are other problems besides the ones already reported here or in the issue tracker.
I am especially interested in the issue reported by @marnen (... too many values to unpack...), since it renders the application pretty unusable.

As for the remaining bugs (see [this list](https://github.com/frescobaldi/frescobaldi/issues?q=is%3Aopen+is%3Aissue+label%3Amacosx)), I would appreciate any suggestion.

If you need guidance in running Frescobaldi from source, let me know.
I install Frescobaldi's dependencies with MacPorts.
You can install them also with Homebrew, except for [python-poppler-qt5](https://github.com/frescobaldi/python-poppler-qt5), which you can manually compile and install; @marnen do you think you could provide a formula for python-poppler-qt5 if needed?

**Comment by iilei** [comment]
Thank you @dliessi 
I just tried to run it and it crashed immediately.
Hope [the logs](https://gist.github.com/iilei/c653c21c70eb245057c57a76fa5a399d) help.

**Comment by dliessi** [comment]
@iilei can you try running it again and checking the errore messages in the Console application when it crashes?

**Comment by iilei** [comment]
I just tried reinstalling lilypond with homebrew. Looks like Mac OS Catalina doesn`t work with the Cask

```
❯ brew cask reinstall lilypond
==> Downloading http://lilypond.org/downloads/binaries/darwin-x86/lilypond-2.18.2-1.darwin-x86.tar.bz2
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'lilypond'.
Error: This cask does not run on macOS versions newer than Mojave.
```

**Comment by marnen** [comment]
@dliessi This is awesome news; thanks! I’ll try it out. 

@iilei There’s no 64-bit Mac build of LilyPond yet. I’m working on one, but I could use help (see the dev list archives for more info).

**Comment by marnen** [comment]
@dliessi:
> @marnen do you think you could provide a formula for python-poppler-qt5 if needed?

I have no idea. Why do you think I might be able to? (It’s possible, but I’m not sure why you asked me specifically.)

**Comment by dliessi** [comment]
@marnen:
> Why do you think I might be able to? (It’s possible, but I’m not sure why you asked me specifically.)

You originally provided the formula for Frescobaldi and python-poppler-qt4, so I just thought you probably have enough knowledge of Homebrew to write a formula for python-poppler-qt5.
I remember that there were some problems earlier in building python-poppler-qt5, but now it can be built manually or via MacPorts, so I expect that we could solve any remaining build problems.
I would do it myself, if needed, but I don't use Homebrew and have little knowledge of its internal details.
I could give it a try, though.

**Comment by marnen** [comment]
@dliessi I forgot that I provided the python-poppler-qt4 formula. :) I could indeed probably do a similar one for qt5. 

I do suggest getting familiar with Homebrew, though. For most use cases that I’m familiar with, it’s far better than the alternatives.

**Comment by marnen** [comment]
@dliessi I just tried Fresco 3.1 on Mojave. The exact same bugs are still there (truncated tab titles, "too many values to unpack" when doing anything with the Session menu). In addition, I got the following error message when attempting to pinch-zoom the PDF view:

<details>

```
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/qpageview/link.py", line 196, in event
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/qpageview/view.py", line 1015, in event
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/qpageview/view.py", line 1030, in handleGestureEvent
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/qpageview/view.py", line 1047, in pinchGesture
NameError: name 'QPinchGesture' is not defined
```

</details>

I really appreciate your effort in packaging this, but the continued presence of these bugs mean that this build isn't any more usable than the 3.0 build.

**Comment by dliessi** [comment]
@marnen:

> truncated tab titles

In https://github.com/frescobaldi/frescobaldi/issues/1087#issuecomment-410942325 there is a minimal example of the problem.
I suspect this is a bug in either Qt or PyQt: I haven't yet reported it to those projects, but I will do it soon.

> "too many values to unpack" when doing anything with the Session menu

I still cannot reproduce the issue.
I added it as #1237.
Maybe Wilbert will have some ideas.

> In addition, I got the following error message when attempting to pinch-zoom the PDF view: [...]

This is solved in current master (see #1234 and 6365b6d7cbc42ed9145d7b0b0394482c479b316b).
However, the pinch gesture zoom is not behaving very well if the pinch is too slow: I'll investigate it.

**Comment by marnen** [comment]
FWIW, I don't so much care if the pinch gesture is supported (though it would be nice) as that it not bring up an error. :)

**Comment by dliessi** [comment]
Dear all,
the application bundle for Frescobaldi 3.1.1 is now [available](https://github.com/frescobaldi/frescobaldi/releases/tag/v3.1.1).

A few bugs have been solved.
Moreover the application bundle is now built with Qt 5.14, which should work on macOS 10.15 Catalina, where some users previously reported immediate crash at startup.

However, there are still several [open issues](https://github.com/frescobaldi/frescobaldi/issues?q=is%3Aopen+is%3Aissue+label%3Amacosx), including the ones reported for the new application bundle.
In particular, convert-ly is still broken on macOS 10.15 Catalina (see #1232) and I still expect problems in running the application on macOS 10.12 Sierra (see #1233).

Please test the new build and report about new and existing issues.
Thanks.

**Comment by dliessi** [comment]
One of the main problems with the current build of the app bundle is #1244 (QtWebEngine is not packaged correctly, so Frescobaldi crashes whenever the documentation browser of the SVG viewer are opened).
In https://github.com/frescobaldi/frescobaldi/issues/1244#issuecomment-581360015 I provide minimal test files and some references.
Any help is appreciated, but I will ask for help also from py2app.

**Comment by iilei** [comment]
Finally I managed to get the latest version running on my mac. As i am using [asdf-vm](https://github.com/asdf-vm/asdf) for managing python versions and also homebrew for some cli tools, I think my setup has led to a few quirks.

Basically I wanted to thank you all for maintaining frescobaldi and having it OSX compatible. 🙂

**Comment by dliessi** [comment]
Since some people are still on 10.11 El Capitan or 10.12 Sierra, I added to the [release page for 3.1.2](https://github.com/frescobaldi/frescobaldi/releases/tag/v3.1.2) a build made on 10.11 El Capitan: it should work on that version of macOS and any later version.
The build is for the already released version 3.1.2, so it still contains the workaround for #1244 (instead of a working QtWebEngine) and lacks the latest fixes related to running the Python tools.

**Comment by dliessi** [comment]
> [...] so it still contains the workaround for #1244 (instead of a working QtWebEngine) [...]

The way I wrote this sentence may suggest that #1244 is solved in current master.
**It is not**, and I don't expect a solution in the near future.
Any help is appreciated.

Besides looking for a solution to the packaging bug, adding Frescobaldi (and python-poppler-qt5) to Homebrew as a formula built from source (instead of the current cask installing our prebuilt application bundle) would work around the issue for the many Homebrew users ([more than 400 installations in the latest year](https://formulae.brew.sh/cask/frescobaldi)).
I'll give it a try soon, but any help is appreciated here as well.

**Comment by marnen** [comment]
Thank you! It looks like this works, without the display bugs that have plagued previous Mac packagings of 3.x, but I'd like to have the documentation browser back before I switch to this version. I've left some comments on #1244; let me know if you need more help.
